### ISSUE TITLE
Support for passing ssh key path/material to conenction

### ISSUE THREAD

**Issue by corvint** [kreuzwerker/terraform-provider-docker#101]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

One can specify a remote host for connecting to a docker daemon like so.

```hcl
provider "docker" {
  host = "ssh://user@remote-host:22"
}
```

However, in a dynamic environment where one spins up a number of VMs in a swarm cluster, the IP addresses might not be known ahead of time or they may not have common host names. One might want to explicitly provide an `ssh` key that isn't configured in their `~/.ssh/config`.

More generally speaking, there are other providers that don't use `ssh` directly but use a `golang` impl which may be preferable.

### New or Affected Resource(s)

* `docker` provider (all resources)

### Potential Terraform Configuration

```hcl
provider "docker" {
  host = "ssh://user@remote-host:22"
  private_key = file(var.my_key_path)
}

// ---- or ----

provider "docker" {
  host = "ssh://user@remote-host:22"
  private_key_path = var.my_key_path
}
``

**Comment by mavogel** [comment]
Hi @corvint , sounds reasonable.

> More generally speaking, there are other providers that don't use ssh directly but use a golang impl which may be preferable.

Do you have links to some examples at other providers? That would be helpful

**Comment by suzuki-shunsuke** [comment]
Related #29

**Comment by corvint** [comment]
You are correct that this is a duplicate. Moving comments to 29.
