### ISSUE TITLE
Support for docker_service having service level labels 

### ISSUE THREAD

**Issue by corvint** [kreuzwerker/terraform-provider-docker#103]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using a `docker_service` resource, the `container_spec.labels` field (naturally) only applies labels to a container itself and not the service. There is no way to easily apply labels to the service.

### New or Affected Resource(s)

* `docker_service`

### Potential Terraform Configuration

```hcl
resource "docker_service" "foo" {
  name = "foo-service"
  task_spec {
    container_spec {
      image = "repo.mycompany.com:8080/foo-service:v1"

      labels {
        name = "some.container.label"
        value = "foo"
    }
  }

  // this is the proposed change
  labels {
    name = "some.service.label"
    value = "bar"
  }
}
```

**Comment by suzuki-shunsuke** [comment]
@corvint Thank you for your report.

The service level labels is already supported, but I found that this attribute isn't documented.

https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/service#argument-reference

I'll update the document.

```hcl
resource "docker_image" "alpine" {
  name = "alpine:3.11.6"
}

resource "docker_service" "foo" {
  name = "foo-service"
  task_spec {
    container_spec {
      image   = docker_image.alpine.latest
      command = ["tail"]
      args    = ["-f", "/dev/null"]

      labels {
        label = "some.container.label"
        value = "foo"
      }
    }
  }
  // this is the proposed change
  labels {
    label = "some.service.label"
    value = "bar"
  }
}

terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.9.0"
    }
  }
}

# Configure the docker provider
provider "docker" {
}
```

**Comment by suzuki-shunsuke** [comment]
#105

**Comment by Mayeu** [comment]
@suzuki-shunsuke Hello :) I'm trying to set labels at the service levels with the 2.9.0 version of the provider (as in your example), but I always get:
```
Error: Unsupported block type
```

Are you sure this is supposed to work in 2.9.0?

**Comment by mavogel** [comment]
@Mayeu it will work in the next release which will come in the next days. 
Until then you can build the `master` branch locally and test as described [here](https://github.com/kreuzwerker/terraform-provider-docker/blob/master/CONTRIBUTING.md#test-against-current-terraform-iac-descriptions)

HTH

**Comment by suzuki-shunsuke** [comment]
I confirmed the above example works as expected. https://github.com/kreuzwerker/terraform-provider-docker/issues/103#issuecomment-752055852

```
$ terraform version
Terraform v0.13.5
+ provider registry.terraform.io/kreuzwerker/docker v2.9.0
```

Please tell us the version of Terraform.

**Comment by suzuki-shunsuke** [comment]
And please tell us the command and command full output.

**Comment by Mayeu** [comment]
@suzuki-shunsuke: hmmm, I was going to copy all that here, but it sudently started to work 🤔

For completion sake:
```
➜ uname -a
Darwin Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

➜ terraform version
Terraform v0.14.3
+ provider registry.terraform.io/kreuzwerker/docker v2.9.0

# Docker version on the targeted swarm
$ docker --version
Docker version 20.10.1, build 831ebea
```

I assume you can close the ticket then ¯\\\_(ツ)\_/¯

**Comment by mavogel** [comment]
alright, thanks for the clarification both of you :)
