### ISSUE TITLE
Support for MaxReplicas in Task Spec Placement Configuration

### ISSUE THREAD

**Issue by andymotta** [kreuzwerker/terraform-provider-docker#111]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since [v1.40](https://docs.docker.com/engine/api/v1.40/#operation/ServiceCreate) of the Docker Engine API, we are able to set MaxReplicas on a service in order to spread certain tasks more evenly.  Upon inspection of the placement schema, it doesn't seem like this feature was ever added to the provider.  Can we add this to the latest version of the provider?  It could really simply configuration for us, thank you!

API Reference: 

### New or Affected Resource(s)

* docker_service

### Potential Terraform Configuration

```hcl
    placement {
      max_replicas = 1
    }
```

**Comment by suzuki-shunsuke** [comment]
#112

**Comment by andymotta** [comment]
> #112

Thank you!!
