### ISSUE TITLE
Building with tagless name fails with "invalid reference format"

### ISSUE THREAD

**Issue by hectorj** [kreuzwerker/terraform-provider-docker#116]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

```Terraform v0.14.3
+ provider registry.terraform.io/kreuzwerker/docker v2.9.0
```

### Affected Resource(s)

* `docker_registry_image`

### Terraform Configuration Files

```hcl
resource "docker_registry_image" "eshopwebmvc" {
  name = "eu.gcr.io/my-project-id/my-image-name"

  build {
    context    = "."
  }
}
```

### Expected Behaviour

Docker image built and pushed

### Actual Behaviour

`Error: Error building docker image: Error response from daemon: invalid reference format`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I did a bit of debugging, and providing a name without a tag gives this `internalPushImageOptions` 
```
{
    Name: eu.gcr.io/my-project-id/my-image-name
    FqName: eu.gcr.io/my-project-id/my-image-name: 
    Registry: eu.gcr.io 
    NormalizedRegistry: https://eu.gcr.io
    Repository: my-project-id/my-image-name
    Tag:
}
```

Note the `:` at the end of `FqName`.

Building and pushing directly via Docker, it accepts `eu.gcr.io/my-project-id/my-image-name` and assumes `eu.gcr.io/my-project-id/my-image-name:latest`, so I expected the same behavior here.

I see a few possible solutions:
 - strip the final `:` from `FqName`
 - set a default `latest` tag
 - return a more precise error to tell the user to always provide a tag

**Comment by suzuki-shunsuke** [comment]
Thank you for your report.

**Comment by suzuki-shunsuke** [comment]
I have sent a pull request #117
