### ISSUE TITLE
Forced container replacement (Regression?)

### ISSUE THREAD

**Issue by saitho** [kreuzwerker/terraform-provider-docker#118]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

Terraform v0.13.3
+ provider registry.terraform.io/kreuzwerker/docker v2.8.0

### Affected Resource(s)

* `docker_container`

### Issue

I'm applying the plans regularly in order to keep the Docker containers up-to-date (via docker_image data structure).
However I noticed my containers get replaced everytime because of internal fields ("working_dir", "user" in my case).

In June 2020 this error was already reported (https://github.com/hashicorp/terraform-provider-docker/issues/242) and fixed in [this](https://github.com/hashicorp/terraform-provider-docker/pull/269) and [that](https://github.com/hashicorp/terraform-provider-docker/pull/272) pull request.

Apparently this fix was removed with v2.8.0: https://github.com/kreuzwerker/terraform-provider-docker/commit/cdc0d912cc7f44400e587a997594e83688dc0430

### Expected Behaviour

* Settings like "user" and "working_dir", which are set by the container, **do not** result in a replacement when applying the Terraform plan.

### Actual Behaviour

Settings like "user" and "working_dir", which are set by the container, result in a replacement when applying the Terraform plan.

```
      - user              = "solr" -> null # forces replacement
      - working_dir       = "/opt/solr" -> null # forces replacement
```

### Steps to Reproduce

1. Create a new Docker container resource from any image defining a working directory (e.g. "typo3solr/ext-solr:10.0.1")
2. Apply the plan two times. The container should be recreated, even though nothing changed.

**Comment by suzuki-shunsuke** [comment]
Please try to use the latest version v2.9.0 .
#14

**Comment by saitho** [comment]
Oh sorry, I only checked the Changelog and didn't see it mentioned there.
So I assumed that was still a thing. Will test with 2.9.0 and close the issue if it works.

**Comment by saitho** [comment]
Yes, that worked! Thanks.
