### ISSUE TITLE
CI of website fails

### ISSUE THREAD

**Issue by suzuki-shunsuke** [kreuzwerker/terraform-provider-docker#12]
https://github.com/kreuzwerker/terraform-provider-docker/pull/8#issuecomment-736970642

https://github.com/hashicorp/terraform-website/blob/e6439bbe509a184aa06a711e5db2c050a150690e/content/scripts/check-links.sh#L34-L47

**Comment by mavogel** [comment]
it has probably something to do with the migration of the repository and the read-only mode of the old repo. I asked some HashiCorp folks about it

**Comment by mavogel** [comment]
Update:

> yeah, you can just remove all the website stuff, a number of repos have moved to things like this for link checking: https://github.com/gaurav-nelson/github-action-markdown-link-check
(AWS uses it as an example)

So we could update the flow and use https://github.com/terraform-providers/terraform-provider-aws as an example
Can you do that @suzuki-shunsuke ?

**Comment by suzuki-shunsuke** [comment]
Sure. I'll try it later.

ref. https://github.com/hashicorp/terraform-provider-aws/search?q=github-action-markdown-link-check
