### ISSUE TITLE
docker_image build doesn't work for remote docker daemon

### ISSUE THREAD

**Issue by drobert-bfm** [kreuzwerker/terraform-provider-docker#121]
it looks like "build" on docker_image don't work when connecting to a remote docker daemon, either via http(s) or ssh. It looks like the context isn't being sent over to the remote server somehow, because it consistently fails with the error:

Error response from daemon: Cannot locate specified Dockerfile

It does not matter what value I put for "path" and "dockerfile", it always fails with the same message, with only the path to the Dockerfile changing.

**Comment by mavogel** [comment]
Hi @drobert-bfm, can you put your issues into one of the issue templates please and provide more information on
- how is your setup of the docker daemon
- how does the `tf` file look like
- what commands did you run 
- current and expected behaviour.

Thanks

**Comment by john-terrell** [comment]
Perhaps a clue:  "build" doesn't work for me on a Windows host but works fine on a Mac host.   @drobert-bfm  - are you running on Windows?

**Comment by drobert-bfm** [comment]
The problem related to running a remote docker instance. I don't think it's related to the client's OS. But yes, I'm running from Windows to a Linux VM docker host.



[cid:bfm2017_891662ee-08e2-4c2c-afa4-4f8d1ece2f5e.png]

Denis Robert
Senior Solutions Architect

BF&M Limited
Phone: (441) 295-5566 ext. 5558



This message and any attachment(s) are intended only for the use of the person or entity to which they are addressed and may contain confidential and/or proprietary information. If you received this transmission in error, please alert the sender by reply e-mail immediately and delete it from your computer system. Opinions, conclusions and other information in this e-mail and any attachments that do not relate to the official business of the Company are neither given nor endorsed by it.

www.bfm.bm<http://www.bfm.bm/> | Facebook<https://www.facebook.com/bfmlimited> | Twitter<https://twitter.com/bfminsurance> | LinkedIn<https://www.linkedin.com/company/875146?trk=companies_home_ycp_see_cp_bf%26m-insurance-group> | Instagram<https://www.instagram.com/bfminsurance/>



________________________________

**Comment by john-terrell** [comment]
Correct.     If I attempt to build from a Windows host (running terraform) to a Linux docker host, it fails.   Doing the same from a MacOS host (running terraform) to a Linux docker host succeeds.

**Comment by davidia** [comment]
Can confirm this only happens on windows, same code works from linux.

**Comment by martijnvanderkamp** [comment]
Does anyone have a work-around for this other than buying a macbook?

**Comment by andrekiba** [comment]
same problem, is there a way to use it on windows (with docker desktop for example) ?

**Comment by Junkern** [comment]
Closing this. We heavily improved the handling of the `build` attribute of `docker_image` in the past 6 months and there are more improvements coming
Please open a new issue in case you are running into problems :)
