### ISSUE TITLE
remote-exec not working

### ISSUE THREAD

**Issue by drobert-bfm** [kreuzwerker/terraform-provider-docker#122]
When attempting to use a remote-exec provisioner along with docker_container, I keep getting:

Error: host for provisioner cannot be empty

there's no attribute to set for the host, so I have to suspect it's internal to the communication between the provisioner and the docker provider.

**Comment by mavogel** [comment]
same as https://github.com/kreuzwerker/terraform-provider-docker/issues/121#issuecomment-757370258

**Comment by drobert-bfm** [comment]
It's not the same as #121, unless the root cause is identical. One has to do with the build operation on docker-image, and the other on remote-exec provisioning.

**Comment by mavogel** [comment]
No, I mean the same as my comment in the other issue. We need more context to fully understand your issue :)

**Comment by suzuki-shunsuke** [comment]
ref. [Provisioner Connection Settings](https://www.terraform.io/docs/provisioners/connection.html)
