### ISSUE TITLE
Error building docker image

### ISSUE THREAD

**Issue by omerlh** [kreuzwerker/terraform-provider-docker#123]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/google v3.52.0
+ provider registry.terraform.io/kreuzwerker/docker v2.10.0

Your version of Terraform is out of date! The latest version
is 0.14.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* `docker_registry_image`

### Terraform Configuration Files

```hcl
resource "docker_registry_image" "importer" {
  name = "${local.image_name}:6"
  build {
    context = "../<>"
  }
}
```

### Panic Output

```
docker_registry_image.importer: Creating...
docker_registry_image.importer: Still creating... [10s elapsed]

Error: Error building docker image: 127: The command '/bin/sh -c yarn build' returned a non-zero code: 127

  on snyk_importer.tf line 9, in resource "docker_registry_image" "importer":
   9: resource "docker_registry_image" "importer" {
```
### Expected Behaviour

Image built correctly, as `docker build ` with the same context works as expected
### Actual Behaviour

Image failed to build 

### Steps to Reproduce

Dockerfile:
```
FROM node

WORKDIR /app

COPY package.json yarn.lock /app/

RUN yarn 

COPY . . 

RUN yarn build

CMD [ "yarn", "start" ]
```

The build failed with weird TSC issue (had to do some hacks to get the actual command error, as there is no access to it by default):
```
yarn run v1.22.5
$ tsc --outDir dist index.ts
/bin/sh: 1: tsc: Too many levels of symbolic links
error Command failed with exit code 127.
```

The solution was to change this line to something like ` rm -rf node_modules && yarn && yarn build`. 
I tried creating a `.dockerignore` file but it was not honored:
```
*/dist/
*/node_modules/
```
### References

* #0000

**Comment by suzuki-shunsuke** [comment]
Sorry for late reply.
Could you tell us minimum code to reproduce the issue?

**Comment by omerlh** [comment]
The dockerfile is in the original message - should be easy to reproduce

**Comment by suzuki-shunsuke** [comment]
The above Dockerfile depends on other files like package.json, yarn.lock, app.
