### ISSUE TITLE
ci: support for windows build

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#125]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We should add support for unit/acceptance tests on windows (e.g. on appveyor)

### New or Affected Resource(s)

* `docker_*`

### References

* #124

**Comment by suzuki-shunsuke** [comment]
https://azure.microsoft.com/en-us/services/devops/pipelines/

Maybe Azure Pipelines is also one option, although I haven't used it yet.

**Comment by suzuki-shunsuke** [comment]
I try to use Azure Pipelines. https://github.com/suzuki-shunsuke/terraform-provider-docker/pull/1

**Comment by suzuki-shunsuke** [comment]
It succeeded to run `make vet` on Azure Pipelines (Windows).
But I don't know how to run `setup_private_registry.bat`, because I don't know Windows.

**Comment by mavogel** [comment]
Great progress. Maybe @tanis80  can support with his windows knowledge :)

**Comment by tanis80** [comment]
> Great progress. Maybe @tanis80 can support with his windows knowledge :)

Free time is the problem, but I'll be happy to help.

**Comment by mavogel** [comment]
adapting `setup_private_registry.bat` would be a great help :)
