### ISSUE TITLE
ci: add matrix build for tf versions 12-14

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#127]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We should add tests for multiple tf versions as proposed in the scaffolding: https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.github/workflows/test.yml#L53

### References

* https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.github/workflows/test.yml#L53
* related to #125

**Comment by suzuki-shunsuke** [comment]
# Investigation about TF_ACC_TERRAFORM_VERSION

https://github.com/hashicorp/terraform-plugin-sdk/issues/446

> `TF_ACC_TERRAFORM_VERSION` used to download and use a specific version of Terraform

https://github.com/hashicorp/terraform-website/pull/1287

> `TF_ACC_TERRAFORM_VERSION` env var is not included because this functionality doesn't work properly at the moment in parallel situations.

https://github.com/hashicorp/terraform-plugin-sdk/blob/651b26a663d34daed50d135ddd25e170ff6c6aae/internal/plugintest/config.go#L26

https://www.terraform.io/docs/extend/testing/acceptance-tests/index.html#environment-variables

There is no document about `TF_ACC_TERRAFORM_VERSION`.

In some repositories `TF_ACC_TERRAFORM_VERSION` is used.

* https://github.com/search?q=TF_ACC_TERRAFORM_VERSION&type=code
* https://github.com/search?q=org%3Ahashicorp+TF_ACC_TERRAFORM_VERSION&type=code

https://github.com/hashicorp/terraform-provider-helm/blob/41346344841a056327a1dc100ecaf90679f7ab05/.github/workflows/tests.yaml#L25-L28

https://github.com/hashicorp/terraform-provider-helm/actions/runs/494517954

It looks good.

![image](https://user-images.githubusercontent.com/13323303/105559499-b0d02880-5d54-11eb-9089-0968b783867e.png)

**Comment by suzuki-shunsuke** [comment]
#129

**Comment by suzuki-shunsuke** [comment]
Hmm...

`TF_ACC_TERRAFORM_VERSION` doesn't work as expected.

It tested with Terraform v0.11.14 and expected the test failed, but actually test succeeded.

https://github.com/kreuzwerker/terraform-provider-docker/blob/cb0b709a6ba4897678cf4ea84f06000f108c871f/docker/resource_docker_container_test.go#L1789-L1798

https://github.com/kreuzwerker/terraform-provider-docker/blob/cb0b709a6ba4897678cf4ea84f06000f108c871f/docker/resource_docker_container_test.go#L56-L64

```
$ TF_ACC_TERRAFORM_VERSION=0.11.14 TF_ACC=1 go test -v -run AccDockerContainer_basic ./docker
=== RUN   TestAccDockerContainer_basic
--- PASS: TestAccDockerContainer_basic (1.35s)
=== RUN   TestAccDockerContainer_basic_network
--- PASS: TestAccDockerContainer_basic_network (17.00s)
PASS
ok  	github.com/terraform-providers/terraform-provider-docker/docker	18.690s
```

**Comment by mavogel** [comment]
Hmm, ok that's weird. I asked in the `committers-terraform` slack channel

**Comment by mavogel** [comment]
I re-pinged in the channel

**Comment by mavogel** [comment]
> but what I suspect might be happening here is some false positive behavior with Terraform CLI versions prior to 0.12.26, which is the minimum supported version for the binary acceptance testing framework. The SDK does not explicitly error when using earlier versions, so its behavior is undefined. Please also note that most HashiCorp maintained Terraform Providers are now only officially supported on Terraform CLI version 0.12 and later, which we would strongly encourage for other providers as well.

So IMHO we'd support only versions `>=0.12`. WDYT?

**Comment by suzuki-shunsuke** [comment]
Oh, I see.

> So IMHO we'd support only versions >=0.12. WDYT?

I agree.
