### ISSUE TITLE
Support to just build containers with docker_registry_image (without pushing)

### ISSUE THREAD

**Issue by smetj** [kreuzwerker/terraform-provider-docker#130]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be useful to have a resource which just builds the container on the Docker daemon without pushing it to a registry.
This would allow one to manage the build and provisioning cycle restricted to that Docker daemon without the need of/dependency on an external registry service.  This could be useful for testing purposes amongst other use cases.

`docker_registry_image` is already capable of building an image but it's implied that once build, the image is pushed to a registry. It would be useful to have a toggle which prevents the uploading part and keeps the container image locally to the Docker daemon.

The `docker_container` resource could be instructed then to use that particular image, which is then already available locally. 
 
### New or Affected Resource(s)

* docker_registry_image

### Potential Terraform Configuration

```hcl
resource "docker_registry_image" "postfix" {
  name = "postfix"
  build {
    context = "images/postfix"
  }
  push = false
}
```

### References
None
* #0000

**Comment by jfportalb** [comment]
I believe the `docker_image`resource already does it for you. 
https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/image

**Comment by JelleSmet-TomTom** [comment]
You are totally right. This ticket can be closed.

**Comment by smetj** [comment]
You are totally right, ... this ticket can be closed!
