### ISSUE TITLE
Bind ports to ipv6 and ipv4 by default

### ISSUE THREAD

**Issue by stoically** [kreuzwerker/terraform-provider-docker#131]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently when defining ports it binds to the `0.0.0.0` by default, which only binds to ipv4. It'd desirable that it binds to ipv6 as well, similar to how `docker run -p 80:80` works when ipv6 is enabled in the docker configuration.

### New or Affected Resource(s)

* docker_container

### Potential Terraform Configuration

```hcl
  ports {
    external = 80
    internal = 80
  }
```

### Workaround

It is already possible to bind to ipv4 and ipv6 by specifying

```hcl
  ports {
    ip = "[::]"
    external = 80
    internal = 80
  }
```

though, not sure why this works. `docker run -p [::]:80:80` only binds to ipv6, not ipv4.

**Comment by suzuki-shunsuke** [comment]
The default value of `ip` is `0.0.0.0`.

https://github.com/kreuzwerker/terraform-provider-docker/blob/8da701db26ba83ab95b6a0abc49b8dc7c6ec778f/docker/resource_docker_container.go#L413

**Comment by lifeofguenter** [comment]
Analogue discussions:

* https://github.com/ansible-collections/community.docker/issues/70
* https://github.com/moby/moby/issues/41699

E.g. this unfortunately breaks when upgrading from 19.x to 20.x if you were expecting your container to listen both on IPv4 + IPv6

**Comment by Lexy2** [comment]
Actually, this is not only a feature request but also an issue.
If I wanted to bind different IPv4 and IPv6 ports, I would not be able to do it.
```terraform
    ports {
      ip = "0.0.0.0"
      external = 8079
      internal = 80
    }

    ports {
      ip = "[::]"
      external = 8078
      internal = 80
    }
```
because `ip = "[::]"` binds the IPv4 port anyway, and I end up with both 8078 and 8079 bound to TCPv6 and 8079 to IPv4.
If you try to create this configuration, it would store the state incorrectly, adding the following lines to the .tfstate file:
```json
"ports": [
              {
                "external": 8079,
                "internal": 80,
                "ip": "0.0.0.0",
                "protocol": "tcp"
              },
              {
                "external": 8079,
                "internal": 80,
                "ip": "0.0.0.0",
                "protocol": "tcp"
              },
              {
                "external": 8079,
                "internal": 80,
                "ip": "0.0.0.0",
                "protocol": "tcp"
              }
            ],
```

Applying this configuration destroys the container and recreates it every time:
```
      ~ ports { # forces replacement
          ~ external = 8079 -> 8078 # forces replacement
          ~ ip       = "0.0.0.0" -> "[::]" # forces replacement
            # (2 unchanged attributes hidden)
        }
      - ports { # forces replacement
          - external = 8079 -> null
          - internal = 80 -> null # forces replacement
          - ip       = "0.0.0.0" -> null
          - protocol = "tcp" -> null
        }
        # (1 unchanged block hidden)
```

There is an additional side effect of that mishap.
If I wanted to import an existing `docker_container` configuration (bound to `-p 8079:80` initially) into terraform state, terraform would see the IPv4 and IPv6 ports incorrectly:
```json
            "ports": [
              {
                "external": 8079,
                "internal": 80,
                "ip": "::",
                "protocol": "tcp"
              },
              {
                "external": 8079,
                "internal": 80,
                "ip": "::",
                "protocol": "tcp"
              }
            ],
```
, failing to reuse this state in future and producing
`Error: Unable to start container: Error response from daemon: Ports are not available: listen tcp :8079: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.` message.

**Comment by Lexy2** [comment]
Alright, delved into the code and found a thing that @mavogel may be interested in.

The thing is that `READ` checks the bound ports from `container.NetworkSettings.Ports` that can be different to what you configure for Docker to use. If you just bind `docker run -p 80:80 image`, the client will bind TWO addresses on the host: an IPv4 one and an IPv6 one (if required, unless you explicitly specify the IP address, of course).
This leads to saving 2 host port entries into `terraform.tfstate` when the configuration defines only 1 `ports` section, and forces terraform to recreate the container at every apply, even if there were no changes to the configuration.

**Comment by mavogel** [comment]
Thank @Lexy2 for pointing on the details. Related to #88

**Comment by tomalok** [comment]
In general, he terraform provider should act exactly the same as how `docker` itself does.  Please note that IPv6 support in Docker isn't quite on par with IPv4, and (last I checked) was still a work in progress.
