### ISSUE TITLE
Support for AWS registry

### ISSUE THREAD

**Issue by gaborbalogh1** [kreuzwerker/terraform-provider-docker#132]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Push the created image to AWS ECR as it is not currently documented and Local exec doesn't seem to work.

### New or Affected Resource(s)

AWS ECR
Docker 
Terraform 0.14.5

# to push an image you need to log in to public registry like AWS, Azure, GCP
# build the image - working
# tag the image - working
# push the image  - not working

### Potential Terraform Configuration

Any way to expand capabilities and push the image directly from this module? If you can already do this please provide the resource I can use for this purpose? 

provider "docker" "push" {

tag or repository url = repository url:tag

}

**Comment by suzuki-shunsuke** [comment]
These comments may be helpful.

* https://github.com/kreuzwerker/terraform-provider-docker/issues/3#issuecomment-737228554
* https://github.com/kreuzwerker/terraform-provider-docker/issues/3#issuecomment-737245156

**Comment by gaborbalogh1** [comment]
thanks for the pointers but I still have a problem with the authentication even after configuring the 
credential settings in docker/config.json and docker/dameon.json files. Could you help with providing a working example of how the json file should look like?

Thanks,

**Comment by mavogel** [comment]
And we'd also add it to the examples folder

**Comment by gaborbalogh1** [comment]
Hi 

Just wanted to let you know that it is now working as expected after updating the configuration as detailed in the 2 links you sent also would help if you have a way of updating ecr tokens I dont see it in your documentation?

Thanks,

**Comment by gaborbalogh1** [comment]
Its all working now thanks for your help.
