### ISSUE TITLE
Unable to access insecure (local) repositories

### ISSUE THREAD

**Issue by JoeHitchen** [kreuzwerker/terraform-provider-docker#135]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

Terraform v0.14.7
+ provider registry.terraform.io/kreuzwerker/docker v2.11.0

### Affected Resource(s)

* `data.docker_registry_image`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    docker = {
      source = "kreuzwerker/docker"
      version = "2.11.0"
    }
  }
}

provider "docker" {
  host = "tcp://dockerd.outpost:2375/"
}

data "docker_registry_image" "target" {
  name = "registry.outpost/mock:2.1.0"
}
```

### Debug Output

```
Error: Got error when attempting to fetch image version from registry:
Error during registry request: Get "https://registry.outpost/v2/mock/manifests/2.1.0":
x509: certificate signed by unknown authority
 on main.tf line 16, in data "docker_registry_image" "target":\n  16: data "docker_registry_image" "target"
 ```

### Hoped-for Behaviour

I am trying (but struggling) to access a local insecure registry. After reading various resources, it seems that this provider is hard-coded to use HTTPS for registry connections, and a connection with an HTTP registry is impossible. I have added a self-signed certificate to my registry and was first met with
```
Got error when attempting to fetch image version from registry:
Error during registry request: Get "https://registry.outpost/v2/mock/manifests/2.1.0":
x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
  on main.tf line 16, in data "docker_registry_image" "target"
```
I added the recommended environment variable, but now have the above error message `x509: certificate signed by unknown authority` and have not found any guidance on how to get past it.

I have the configuration in place to allow the Docker daemon to connect to the registry using either HTTP or the self-signed HTTPS, so something seems to not be syncing up with the provider's configuration.

**Comment by mavogel** [comment]
@JoeHitchen you might want to use the `insecure_skip_verify = true` attribute of the newly released `v2.13.0`. We introduced and use this also in our test setup with a local registry and self-signed certificate.

**Comment by JoeHitchen** [comment]
Hi @mavogel - Yes, using `insecure_skip_verify = true` I was able to get my set up working with a self-signed certificate, so thank you for putting that in place! It would be nice if it was possible to connect to bare HTTP repositories too, but I understand if that is an unimportant or undesirable change :)

**Comment by mavogel** [comment]
I mean, if you desire this change we can implement it. Do you? :)
Feel also free to set up a test case. I'm happy to support you.

**Comment by JoeHitchen** [comment]
I had a much more thorough play over the weekend and managed to work through all the remaining disadvantages I felt self-signed HTTPS had compared to HTTP, so I don't feel you need to add this just for my benefit :) Thanks for all your work on this provider though!
