### ISSUE TITLE
add documentation generation

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#143]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The documentation can be generated from the schema
- move the documentation into the `docs` folder
- see https://github.com/hashicorp/terraform-plugin-docs 
- add a hint to https://registry.terraform.io/tools/doc-preview
- see: https://www.terraform.io/docs/registry/providers/docs.html#generating-documentation
- use `go generate` from https://github.com/hashicorp/terraform-provider-scaffolding to have an example implementation
- see https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/GNUmakefile#L127
- see https://github.com/hashicorp/terraform-provider-aws/blob/master/GNUmakefile#L113
- see also https://github.com/bflad/tfproviderdocs

### New or Affected Resource(s)

* docker_*

### References

* #94 
* https://github.com/hashicorp/terraform-provider-scaffolding

**Comment by suzuki-shunsuke** [comment]
In progress #193
