### ISSUE TITLE
replace loops with StateChangeConf

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#144]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

- The for `loops` are only a workaround. Use the `stateFunc` instead
- there are already examples in the code

### New or Affected Resource(s)

* docker_*

### References

* #94

**Comment by suzuki-shunsuke** [comment]
Maybe does your `stateFunc` mean [StateChangeConf](https://www.terraform.io/docs/extend/resources/retries-and-customizable-timeouts.html#statechangeconf)?

https://github.com/kreuzwerker/terraform-provider-docker/blob/6b0f977735dbc2ff99faa9278f4d51f2bf077b02/internal/provider/resource_docker_container_funcs.go#L532

We should wait for creating a container with StateChangeConf.

e.g.

https://github.com/kreuzwerker/terraform-provider-docker/blob/6b0f977735dbc2ff99faa9278f4d51f2bf077b02/internal/provider/resource_docker_service_funcs.go#L57-L64

**Comment by mavogel** [comment]
Yes, you're right. They changed the name in the sdk v2
