### ISSUE TITLE
refactor tests

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#145]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

- refactor tests for readability and consistency (e.g. replace `node` http servers with more lightweight `go` ones): 3af7316
- remove non-working/skipped tests
- think of let's encrypt certificate and remove `InsecureRegistries` workaround for ACC tests or add a flag to the config of the resource: ba1bf41

### New or Affected Resource(s)

* docker_*

### References

* #94

**Comment by mavogel** [comment]
@suzuki-shunsuke how about moving some of the larger test specs out into separate `*.tf` files which would benefit in 
- smaller `*_test.go` files (especially for `service`)
- and we could run a formatted on them

WDYT?

**Comment by suzuki-shunsuke** [comment]
Sorry for late reply. I overlooked.

> @suzuki-shunsuke how about moving some of the larger test specs out into separate `*.tf` files which would benefit in
> 
> * smaller `*_test.go` files (especially for `service`)
> * and we could run a formatter on them or use `terrafmt fmt ./internal/provider --pattern '*._test.go'` to format
> 
> WDYT?

I agree. Good idea.
