### ISSUE TITLE
Make the difference between docker_image and docker_registry_image clear

### ISSUE THREAD

**Issue by suzuki-shunsuke** [kreuzwerker/terraform-provider-docker#153]
* https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/image
* https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/registry_image

I feel it's difficult to understand the difference between docker_image and docker_registry_image.
We should update the document.

* https://github.com/kreuzwerker/terraform-provider-docker/issues/130#issuecomment-776879993

**Comment by suzuki-shunsuke** [comment]
In my understanding,

## What is managed?

* `docker_image`: local image
* `docker_registry_image`: image on Docker Registry

## Building Docker image

Both `docker_image` and `docker_registry_image` supports to build images.

## Pushing Docker image to Docker Registry

* `docker_image`: don't push
* `docker_registry_image`: push

## Usecase

Use `docker_image` to specify images for `docker_container` and `docker_service`.
Use `docker_registry_image` to build and push images.

**Comment by mavogel** [comment]
IHMO we'd merge those together and reuse code from the cli (see #146)

**Comment by Skp2608** [comment]
I want to work on it.

**Comment by Skp2608** [comment]
I want to work on it.
