### ISSUE TITLE
Support for docker_image build_triggers 

### ISSUE THREAD

**Issue by mishak87** [kreuzwerker/terraform-provider-docker#171]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add complemetary `build_triggers` or `build > triggers` to `pull_triggers`

There is no way to force image build ie. when you update Dockerfile or something in build context. Tracking whole build context would be bit excessive and slow so I propose adding `build_triggers` instead.

### New or Affected Resource(s)

* docker_image

### Potential Terraform Configuration

```hcl
resource "docker_image" "foo" {
    build_triggers = {
    }

    build {
        triggers = {
        }
    }
}
```

**Comment by mishak87** [comment]
FYI right now I am forcing new build by changing one of the `build.tags` items

**Comment by pixie79** [comment]
+1 this would be very useful
