### ISSUE TITLE
Provide manual to deploy to multiple target hosts

### ISSUE THREAD

**Issue by volleynator** [kreuzwerker/terraform-provider-docker#187]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I figured out how to deploy a container to a single target host. However, my use cases wants me to deploy a container to multiple target hosts (Digitalocean droplets in my case). I don't get how to configure the provider for multiple target hosts.

### New or Affected Resource(s)

* docker provider

### Potential Terraform Configuration

This is a simple digitalocean droplet resource which spins up 4 droplets (virtual machines). I want to deploy a container to each of them.

```hcl

locals {
  mongodb_nodes = {
    "mongodb-01" = { id : 0, hostname : "mongodb-01" }
    "mongodb-02" = { id : 1, hostname : "mongodb-02" }
    "mongodb-03" = { id : 2, hostname : "mongodb-03" }
    "mongodb-04" = { id : 3, hostname : "mongodb-04" }
  }
}


resource "digitalocean_droplet" "mongodb" {
  for_each = local.mongodb_nodes

  image              = var.mongodb_vm_image
  name               = each.key
  region             = var.default_region
  size               =  var.default_size
  private_networking = true
  vpc_uuid           = var.vpc_id

  tags = [
    "mongodb",
    each.value.hostname
  ]
}
```

### References
- [DigitalOceanProvider](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs)

**Comment by mavogel** [comment]
Hi @volleynator then you might want to get the endpoints of the docker daemon on each host, and configure a provider for this 

The following is not possible atm (`The provider argument name "for_each" is reserved for use by Terraform in a future version`)
```hcl
provider "docker" {
  for_each = toset(["host1", "host2"])
  alias    = each.key
  host     = each.key
}
```

So you have to define a single provider block for each host
```hcl
provider "docker" {
  alias    = "host1Alias"
  host     = "host1-url
  # more attributes like auth etc.
}
```
and then pass it to each resource
```hcl
resource "docker_container" "nginx" {
  provider = docker.host1Alias
  name     = "mongo"
}
```

HTH Manuel

**Comment by AndreiPashkin** [comment]
@mavogel, it's possible to support this use-case by allowing to override connection details on resource-level. And on resource-level `for_each` is allowed, so it would be possible to iterate over multiple hosts with own docker-daemons.

**Comment by tafaust** [comment]
@mavogel Sorry for the necro bump. Do you have any advice how to do the alias on module level so that I don't have to go through each resource in a module?
Thanks!
