### ISSUE TITLE
Consolidate and migrate from deprecated repository

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#2]
From the old repository: https://github.com/terraform-providers/terraform-provider-docker/issues
- [x] clarify which issues are still relevant
- [x] migrate remaining ones
- [x] close PRs or migrate them
- [x] close / make read only and update link to new one

**Comment by akomic** [comment]
Is this repo going to become home of new official docker provider? @mavogel

**Comment by mavogel** [comment]
This will be the new community maintained one yes

**Comment by colinwilson** [comment]
@mavogel
> * [ ] clarify which issues are still relevant

There's an couple of issues I'd like migrated from the old repo. Is the process managed by you? Can I contribute?

**Comment by mavogel** [comment]
Hey @colinwilson, the process of migrating the issues is coordinated by me. I planned to write a script to dump all of them over but did not find the time yet. Feel free migrate the issues over which are relevant to you :)

**Comment by colinwilson** [comment]
@mavogel Cool. Will do. Thank you. 👍

**Comment by mavogel** [comment]
All remaining issues are migrated. Will label them now
