### ISSUE TITLE
Support for listing current images in ECR/Registry

### ISSUE THREAD

**Issue by felipesere** [kreuzwerker/terraform-provider-docker#204]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great if there was a resource to list all tags for a given image. I believe this supported using `GET /v2/<name>/tags/list`. The data source should return an empty list of there is no such image yet.
My intention is to then use this list to check if a new docker image needs be created for a given tag.

### New or Affected Resource(s)

* docker_registry_image_tags (new)

### Potential Terraform Configuration

```hcl
// Will list all tags tag exist, like 0.0.9, 0.0.10, 0.0.11, ...
data "docker_registry_image_tags" "existing" {
  name = local.ecr_address
}

// "Hardcoded" in shared tfvars, essentially a default. eg. 0.0.10
variable "version" {
  type    = string
  default = "0.0.10"
}

// way to override for testing deployments, e.g. 0.0.10-my-feature
variable "version_override" {
  type    = string
  default = nil
}

locals {
  image_tag = coalesce(var.version_override, var.version)
  ecr_image = format("%v:%v", module.ecr_repository.repository_url, local.image_tag)

  create_image = contains(data.docker_registry_image_tags.existing.image_tags, local.version)
}

resource "docker_registry_image" "main" {
  count = local.create_image ? 0 : 1

  name = local.ecr_image

  keep_remotely = true

  build {
    context = "foo/"
  }
}

module "my-lambda" {
  source = "./modules/lambda"

  function_name = "my-lambda"
  image_uri     = local.create_image ? docker_registry_image.main[0].name : local.ecr_image
}
```

### References

* https://docs.docker.com/registry/spec/api/#listing-image-tags

**Comment by tomalok** [comment]
How about a `docker_registry_images` data source, which by default would list all images at a registry?  `filter` blocks could narrow the list per image name, tag, etc.

**Comment by felipesere** [comment]
I have spiked out a very naive `docker_registry_image_tags`. 
Extending this to "any image" might make the responses almost unwieldy?

**Comment by tomalok** [comment]
> Extending this to "any image" might make the responses almost unwieldy?

A "plural" data source with filters is fairly standard among other providers, such as the official `aws` and `oci`...  Using this pattern would also allow us to discover and "introspect" other (possibly non-terraform-managed) things on the Docker server/swarm.

In the case of `docker_registry_images` the expected result would be an array of `docker_registry_image` -- if the array is empty, no matching images were found.

**Comment by felipesere** [comment]
Yeah, let me spike that into my PR to see how it would feel 👍

**Comment by mavogel** [comment]
@felipesere thanks for contibuting! Are you still on this issue?

**Comment by felipesere** [comment]
Yes, but my internet is currently absolutely horrible. If anyone wants to pick it up, it would make my job easier 😄

**Comment by matifali** [comment]
It would be great to list all tags of an image
