### ISSUE TITLE
Error deleting container: context deadline exceeded

### ISSUE THREAD

**Issue by alexkunin** [kreuzwerker/terraform-provider-docker#206]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `docker_service`, maybe others

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.12.2"
    }
  }
}

provider "docker" {
  host = "ssh://my-private-server"
}

resource "docker_service" "example_service" {
  name = "example_service"
  task_spec {
    container_spec {
      image = "nginx:alpine"
    }
  }
}
```

### Debug Output

Here are few relevant lines of debug output:

```
2021-05-27T16:38:22.146+0300 [INFO]  provider.terraform-provider-docker_v2.12.2: 2021/05/27 16:38:22 [INFO] Waiting for container: 'c05fe1a42bea011364ac640c6cf79cf6c7719a657406b4d235ac92e373247ace' to exit: max 0s: timestamp=2021-05-27T16:38:22.146+0300
2021-05-27T16:38:22.147+0300 [INFO]  provider.terraform-provider-docker_v2.12.2: 2021/05/27 16:38:22 [INFO] Container exited with code [0xc0003643c0]: 'c05fe1a42bea011364ac640c6cf79cf6c7719a657406b4d235ac92e373247ace': timestamp=2021-05-27T16:38:22.146+0300
2021-05-27T16:38:22.147+0300 [INFO]  provider.terraform-provider-docker_v2.12.2: 2021/05/27 16:38:22 [INFO] Removing container: 'c05fe1a42bea011364ac640c6cf79cf6c7719a657406b4d235ac92e373247ace': timestamp=2021-05-27T16:38:22.146+0300
2021-05-27T16:38:22.149+0300 [DEBUG] provider.terraform-provider-docker_v2.12.2: time="2021-05-27T16:38:22+03:00" level=warning msg="commandConn.CloseWrite: commandconn: failed to wait: signal: killed"
╷
│ Error: Error deleting container c05fe1a42bea011364ac640c6cf79cf6c7719a657406b4d235ac92e373247ace: Delete "http://docker/v1.41/containers/c05fe1a42bea011364ac640c6cf79cf6c7719a657406b4d235ac92e373247ace?force=1&v=1": context deadline exceeded
```

And here is the full log: https://gist.github.com/alexkunin/d3d17afebcd881909d127ff329ee7e67

### Expected Behaviour

Containers should be deleted reliably, without errors.

### Actual Behaviour

Terraform exited with error message, though containers were actually deleted.

### Steps to Reproduce

As you can see from the config file, Docker is accessed via `ssh`. The server is remote, latency is ~17ms, and in general connection seems to be quite reliable (no connection issues noticed with other software).

So, after doing `init` and `apply`, doing `destroy` fails *sometimes* (I'd say 1 in 3 times). Doing it again right away usually completes successfully. Sometimes `apply` or `plan` can fail with similar errors, but failed deletion is most common.

Just guessing here, but it seems timeouts are set to basically zero, and local docker connection (or faster network connection, probably with additional latency caused by `ssh` wrapper) is usually quick enough to respond in time.

I see that `[INFO] Removing container:` (at 2021-05-27T16:38:22.147+0300) happens in [resource_docker_service_funcs.go:296](https://github.com/kreuzwerker/terraform-provider-docker/blob/6c796e15a5a44e6213b78cc8950af63b9be22641/internal/provider/resource_docker_service_funcs.go#L296), then actual command is sent to server, and in 2 ms (at 2021-05-27T16:38:22.149+0300) there is `commandConn.CloseWrite: commandconn: failed to wait: signal: killed`. After that top level message "Error deleting container" is returned to user (too bad, without timestamp). And that what makes me think the timeout is too short.

Any advice that will help me can make this more reliable would be much appreciated.

**Comment by mavogel** [comment]
Thanks for reporting. Yes, it seems the deadline is too short, because it's maybe the default. Will investigate and try to reproduce

**Comment by alexkunin** [comment]
BTW, same error happens with local connection on Docker Desktop (Mac), test case looks basically the same, but provider block is empty:

```hcl
provider "docker" {
}
```

> Error deleting container 76b76df83fb7090d5af90e3ecf4753f38ba49d96b669eb6cf9464e9d4e528289: Delete "http://%2Fvar%2Frun%2Fdocker.sock/v1.41/containers/76b76df83fb7090d5af90e3ecf4753f38ba49d96b669eb6cf9464e9d4e528289?force=1&v=1": context deadline exceeded

Weird enough, the following line from original issue is nowhere to be found in the log: `level=warning msg="commandConn.CloseWrite: commandconn: failed to wait: signal: killed"` -- probably this is specific to `ssh://` wrapper?

**Comment by mavogel** [comment]
fix is on the way @alexkunin :)
