### ISSUE TITLE
Documentation about accessing Docker service over SSH is misleading

### ISSUE THREAD

**Issue by AndreiPashkin** [kreuzwerker/terraform-provider-docker#219]
In the [docs](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs) the section that is supposed to show how to setup access to the Docker service through SSH is copied from previous example and has nothing to do with SSH.
![Docs-overview-kreuzwerker-docker-Terraform-Registry](https://user-images.githubusercontent.com/4378647/120636084-dfce7780-c475-11eb-858c-2053faac31a9.png)

**Comment by mavogel** [comment]
yes that's right. We fixed the example in #201 which is not released yet. Will come in the next milestone
