### ISSUE TITLE
Provider requires docker to be running even if you aren't doing anything that requires local Docker

### ISSUE THREAD

**Issue by kevinburkemeter** [kreuzwerker/terraform-provider-docker#224]
The configure block that's called by New() checks whether Docker is running locally, which means that this will fail even if all you are using (all I am using personally) is the `docker_registry_image` command to ensure that a reference to a given registry actually exists.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by suzuki-shunsuke** [comment]
Thank you for your report.
I appreciate if you use the issue template https://github.com/kreuzwerker/terraform-provider-docker/issues/new?assignees=&labels=&template=Bug_Report.md .

**Comment by kevinburkemeter** [comment]
I have edited the ticket to include the relevant information. The behaviour is present on the latest master commit; I found it by reading through the code, I suppose that I can include code snippets here. 

To reproduce, try adding a `docker_registry_image` resource and stopping Docker and then running any Terraform action.

**Comment by kevinburkemeter** [comment]
I think I'm going to be able to do what I want using the `http` data module, so I'm going to switch to using that, I think. https://registry.terraform.io/providers/hashicorp/http/latest/docs/data-sources/http

**Comment by mavogel** [comment]
Great! Feel free to reopen the issue if needed.

**Comment by kevinburkemeter** [comment]
Here's that patch just FYI.

```tf
locals {
  docker_image = coalesce(var.image, "meterup/ubuntu:latest")
  docker_repo  = element(split(":", local.docker_image), 0)
  docker_tag   = element(split(":", local.docker_image), 1)
  registry_url = "https://hub.docker.com/v2/repositories/${local.docker_repo}/tags/${local.docker_tag}"
}

# Ensure that the image we're pointing to actually exists
data "http" "docker_image_registry" {
  url = local.registry_url
}
```
