### ISSUE TITLE
Support for specifying platform

### ISSUE THREAD

**Issue by pixie79** [kreuzwerker/terraform-provider-docker#228]
Hi,

When using an M1 mac you can give docker the command --platform linux/amd64 to get enable it to build amd64 version containers rather than arm64. This is very useful where we are building for serverless and pushing as part of terraform especially when testing the pipelines during dev before putting into CI.
Is it / would it be possible to specify overrides to the docker command to enable local building to work?

Currently doing the following
```HCL
resource "docker_registry_image" "docker_image" {
  keep_remotely = false
  name          = "${local.repository_url}/${aws_ecr_repository.repo.name}"
  build {
    build_args = {
      "date" = timestamp()
    }
    context     = var.docker_source
    dockerfile  = "Dockerfile"
    pull_parent = true
  }
}
```
Thanks

Mark

**Comment by mavogel** [comment]
Hi Mark, yes it is possible via the `platform` attribute of the `build` block
```hcl
resource "docker_registry_image" "docker_image" {
  keep_remotely = false
  name          = "${local.repository_url}/${aws_ecr_repository.repo.name}"
  build {
    build_args = {
      "date" = timestamp()
    }
    context     = var.docker_source
    dockerfile  = "Dockerfile"
    pull_parent = true
    platform    = "linux/amd64"
  }
}
```

see https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/registry_image

Let me know if it works for you.

**Comment by pixie79** [comment]
Hi,

Thanks I believe that worked.

Regards

Mark
