### ISSUE TITLE
Image not found when reading a public image from docker hub

### ISSUE THREAD

**Issue by adam-lebon** [kreuzwerker/terraform-provider-docker#229]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

Terraform version :
```
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/kreuzwerker/docker v2.12.2
```

Docker for Mac version :
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

 Server Version: 20.10.6
```

### Affected Resource(s)

* `docker_registry_image`

### Terraform Configuration Files

```hcl
data "docker_registry_image" "ubuntu" {
	name = "ubuntu:latest"
}

output "sha" {
	value = data.docker_registry_image.ubuntu.sha256_digest
}
```

### Debug Output

https://gist.github.com/adam-lebon/27771eb13b0b4966b354e9a6f7d2600a

### Expected Behaviour

The request to the docker registry should succeed 

### Actual Behaviour

The provider cannot read the manifest of the requested image.

The docker hub returns a 404 not found error error. Even if it is a public image.

In the first place, I thought the issue was from the docker hub. But I can't find anything related to the docker hub.

### Steps to Reproduce

1. Create a simple configuration which use a data `docker_registry_image`
2. `terraform plan`

### Important Factoids

Nothing special :
 - Tested from different IP
 - Tested from multiple OS (Docker for Mac + Docker native on ubuntu)
 - Tested manually with curl `curl -vL https://registry.hub.docker.com/v2/library/ubuntu/manifest/latest`

**Comment by eranreshef** [comment]
I'm encountering something similar since last night when trying to access `registry.hub.docker.com/v2/`

**Comment by riisi** [comment]
I just had this happen this morning and was about to raise an issue. I'm wondering if Docker have deprecated `registry.hub.docker.com`. 

I updated to `index.docker.io` with the following configuration and got things working. 

```
provider "docker" {
  registry_auth {
    address  = "index.docker.io"
    username = local.dockerhub_username
    password = local.dockerhub_password
  }
}

data "docker_registry_image" "optic" {
  name = "index.docker.io/myorg/myimage:1.0.0"
}
```

**Comment by adam-lebon** [comment]
You are right, I will put `index.docker.io` in front of all my images as a temporary fix.

```hcl
data "docker_registry_image" "ubuntu" {
	name = "index.docker.io/library/ubuntu:latest"
}

output "sha" {
	value = data.docker_registry_image.ubuntu.sha256_digest
}
```

**Comment by adam-lebon** [comment]
I am looking for some confirmation that the new endpoint is `index.docker.io` before opening a MR

**Comment by eranreshef** [comment]
> I am looking for some official confirmation that the new endpoint is `index.docker.io` before opening a MR

It's very difficult to find such confirmation, I couldn't find any hostname that actually works in the official documentation.

**Comment by adam-lebon** [comment]
> > I am looking for some official confirmation that the new endpoint is `index.docker.io` before opening a MR
> 
> It's very difficult to find such confirmation, I couldn't find any hostname that actually works in the official documentation.

During the past hour, I just realised that so many project are fixing their repos to remove this old URL (doing a global search for issues containing "registry.hub.docker.com" gives a taste of the impact).

I noticed that some people are working with:
- registry.hub.docker.com
- registry-1.docker.io
- index.docker.io

From this comment https://github.com/docker/hub-feedback/issues/2113#issuecomment-865958158_ , we can read:
> [...] but I don't think we provided an official deprecation notice

He also recommend to use **registry-1.docker.io** as registry, but I think we should use the same registry used by our docker clients: **index.docker.io**

**Comment by eranreshef** [comment]
I went ahead with `index.docker.io` for my project.
I also tested all 3 and `registry.hub.docker.com` didn't work for me (returned a 404).
