### ISSUE TITLE
docker_registry_image tag sha256

### ISSUE THREAD

**Issue by pixie79** [kreuzwerker/terraform-provider-docker#231]
If I have the following code this produces me an image in ECR however, best practice for AWS (Checkov) suggests that we should use immutable tags.  As such I would like to set the tag to the sha256. Any ideas how I would do that? it appears at the moment it is set to latest.

```
resource "docker_registry_image" "docker_image" {
  keep_remotely = false
  name          = "${local.repository_url}/${aws_ecr_repository.repo.name}"
  build {
    build_args = {
      "date" = timestamp()
    }
    context     = var.docker_source
    dockerfile  = "Dockerfile"
    pull_parent = true
    platform    = "linux/amd64"
  }
}
```

**Comment by mavogel** [comment]
Hi, you can add the desired tag manually via
```
name          = "${local.repository_url}/${aws_ecr_repository.repo.name}:<tag>"
```
If no tag is given, then `latest` is used by default. Does this answer your question?

**Comment by pixie79** [comment]
Hi

Mostly but do you know how I can get at the sha256 var ? as I would like to use that as the tag.

Thanks

**Comment by mavogel** [comment]
ATM it's not possible to automatically append the `sha256` of the build as the tag. Is this what you want?

**Comment by pixie79** [comment]
Yes, that is exactly what is needed. It would solve the AWS best-practice alert of nuking 'latest' by having IMMUTABLE tags.

Otherwise, I am not sure what I can pin the tag too. I guess if we supported change triggers the other option would be to get a sha256 of the context dir, then if it changes use it as the build trigger and the tag. Not sure if that is possible?

**Comment by pixie79** [comment]
hm, I have half worked around the issue however I now have a bigger issue.

It would appear our CI pipeline still rebuilds sometimes even if the SHA is the same. Then tries to push, i guess because it does not first check if the image exists on the remote. Is there a way to check if the tag already exists before building and then skip?

**Comment by mavogel** [comment]
Currently, we do not have this logic in place to check first if the tag/sha already exists
