### ISSUE TITLE
Add support for docker plugins

### ISSUE THREAD

**Issue by innovate-invent** [kreuzwerker/terraform-provider-docker#24]
Terraform Version

0.13.5
Affected Resource(s)

docker_plugin
Expected Behavior

Configure and manage docker plugins on a daemon
Actual Behavior

Not implemented
References

- https://github.com/hashicorp/terraform-provider-docker/issues/307
- https://github.com/moby/moby/blob/master/api/types/plugin.go
- https://docs.docker.com/engine/reference/commandline/plugin/
- https://github.com/moby/moby/blob/master/client/plugin_install.go

**Comment by suzuki-shunsuke** [comment]
WIP: https://github.com/kreuzwerker/terraform-provider-docker/pull/35

**Comment by suzuki-shunsuke** [comment]
@innovate-invent 

I haven't used Docker plugin, so would you show us the example of Terraform Configuration which you expect.

For example,

```hcl
resource "docker_plugin" "sample-volume-plugin" {
  name  = "tiborvass/sample-volume-plugin:latest"
  # other attributes
  # ...
}
```

**Comment by innovate-invent** [comment]
I would expect the interface to emulate the [docker plugin install command](https://docs.docker.com/engine/reference/commandline/plugin_install/)

```hcl
resource "docker_plugin" "sample-volume-plugin" {
  name  = "tiborvass/sample-volume-plugin:latest"
  alias = "plugin"
  disabled = false
  disable_content_trust = false
  grant_all_permissions = true  # conflicts with the next three options
  network_permissions = ["host"]
  device_permissions = ["/dev/fuse"]
  capabilities = ["CAP_SYS_ADMIN"]
  options = {
    key=value
    ...
  }
}
```

The resource should have attributes that include the values that would be returned by [docker plugin inspect](https://docs.docker.com/engine/reference/commandline/plugin_inspect/). You will also want to create a data source resource that also returns the values of docker inspect. Additionally you should produce a data source that returns a list similar to [docker plugin ls](https://docs.docker.com/engine/reference/commandline/plugin_inspect/) with plugin ids as returned by the api. The inspect data source can then be used to request the details of the listed plugins.

If the docker API supports additional parameters it would be good to forward those too.

One thing you might want to consider is to create the same pattern that is used by the docker_image/docker_container interplay where a resource monitors and updates the plugin image while the other maintains the plugin deployment.
