### ISSUE TITLE
Faild to build docker image depends on the filename in the context directory

### ISSUE THREAD

**Issue by thaim** [kreuzwerker/terraform-provider-docker#245]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

Terraform v0.15.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.48.0
+ provider registry.terraform.io/kreuzwerker/docker v2.13.0

### Affected Resource(s)

* `docker_registry_image`

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.13"

  required_providers {
    aws = ">= 3.35"
    docker = {
      source  = "kreuzwerker/docker"
      version = ">= 2.8.0"
    }
  }
}

provider "aws" {
  region = "eu-west-1"
}

provider "docker" {
  registry_auth {
    address  = local.ecr_address
    username = data.aws_ecr_authorization_token.token.user_name
    password = data.aws_ecr_authorization_token.token.password
  }
}

locals {
  ecr_address = format("%v.dkr.ecr.%v.amazonaws.com", data.aws_caller_identity.this.account_id, data.aws_region.current.name)
}

resource "docker_registry_image" "this" {
  name = "${local.ecr_address}/${aws_ecr_repository.this.name}:latest"

  build {
    context = "context"
  }
}

resource "aws_ecr_repository" "this" {
  name = "sample"
}

data "aws_region" "current" {}
data "aws_caller_identity" "this" {}
data "aws_ecr_authorization_token" "token" {}
```

and context directory as follows
```
context/
|-Dockerfile
|-context

$ cat Dockerfile
FROM scratch

COPY context /context
$ cat context/context 
context
```

### Debug Output

https://gist.github.com/thaim/b33f506ef9521e80177e380ac350fd61

### Panic Output

No crash log

### Expected Behaviour

build docker image and pushed to the ECR repository

### Actual Behaviour

failed to build docker image

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

If I use docker_image resource instead of docker_registry_image, docker image build successfully.

```hcl
resource "docker_image" "this" {
  name = "${local.ecr_address}/${aws_ecr_repository.this.name}:latest"

  build {
    path    = "context"
  }
}
```

Or if I change the filename 'context' to empty, docker_registry_image can build  and push docker image successfully.

```
context/
|-Dockerfile
|-empty

$ cat Dockerfile
FROM scratch

COPY empty /empty
$ cat context/empty
empty
```

It seems that the filename start with the parent directory name failed to build image such as 'contexts` and `context.py` in context directory.

**Comment by mavogel** [comment]
Hi @thaim, thank you for reporting this. I could reproduce the error and it has nothing to do with the name of the directory or file etc. It's about the path to the context directory which needs to be absolute to work -> `context = "${path.cwd}/context"`

Given the following config
```hcl
terraform {
  required_version = ">= 0.13"

  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.13.0"
    }
  }
}

provider "docker" {
  registry_auth {
    address = "127.0.0.1:15000"
  }
}

resource "docker_registry_image" "this" {
  name                 = "127.0.0.1:15000/tf-245:1"
  insecure_skip_verify = true

  build {
    context = "${path.cwd}/context"
  }
}
```

and running in the root of this provider
```console
# to get the local registry
make testacc_setup
# the apply works as desired
terraform apply
```

I will update the documentation for this.
