### ISSUE TITLE
Healthcheck - wait on resource before continuing

### ISSUE THREAD

**Issue by stephenliberty** [kreuzwerker/terraform-provider-docker#247]
Hey folks,

Wanted to know if there was a clear cut way of waiting on a healthcheck to succeed before letting the terraform continue. For example, I've got a dependency on `container_x` that runs a REST call against it. But, it takes a variable amount of time for that container to fully start. It seems this provider considers everything good to go as soon as the container is started, not when the application running in the container is ready.

Suggestions?

Thanks!

**Comment by mavogel** [comment]
Hi, 
for the service resource the `converge_config` fulfills this requirement, but IMHO for `containers` this does not exist yet in  terraform. 
After a quick research, there are various scripts out (e.g. https://github.com/jordyv/wait-for-healthy-container) there parsing the status from `docker inspect ...`

Is this a feature request from your side or a question only?

**Comment by stephenliberty** [comment]
I think we're good. My hope was that you'd consider putting this in as a feature - i.e. `wait_for_healthy` or some such. But, ultimately, I can prevent terraform from moving on by implementing a health check container afterwards, much like the link you sent over.
