### ISSUE TITLE
Support for BuildKit

### ISSUE THREAD

**Issue by Blue-Lamp** [kreuzwerker/terraform-provider-docker#265]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* docker_image

### References

* [Build images with BuildKit](https://docs.docker.com/develop/develop-images/build_enhancements)

**Comment by lamalex** [comment]
Can this please be reopened?

**Comment by QuanTran91** [comment]
When I am building the image using this provider. I got the issue " the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled".
Turn out this provider does not support BuildKit yet.
+1 vote for supporting it.

**Comment by pspot2** [comment]
BuildKit support is activated by setting `version = "2"` in the `build` block. However, building using BuildKit requires the client to first establish an active build session, otherwise the build fails with
```
dockerfile.v0: failed to create LLB definition: no active sessions
```
Therefore still not usable. See also https://github.com/hashicorp/waypoint/issues/1056.
