### ISSUE TITLE
Support for Docker Config Templating

### ISSUE THREAD

**Issue by KristianFJones** [kreuzwerker/terraform-provider-docker#267]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, so I see that this provider doesn't currently allow for specifiying the templating options for Docker Configs, here's the ][CLI/Guide Docs](https://docs.docker.com/engine/swarm/configs/#example-use-a-templated-config) and here's the Param on the [Docker Config Interface with the Go SDK](https://pkg.go.dev/github.com/docker/docker@v20.10.8+incompatible/api/types/swarm#ConfigSpec)

### New or Affected Resource(s)

[resource_docker_config.go](https://github.com/kreuzwerker/terraform-provider-docker/blob/master/internal/provider/resource_docker_config.go#L25-L39)

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "docker_config" "AlpineScriptTest1Entry" {
  name = "alpinelab-scripttest1-${replace(timestamp(), ":", ".")}"
  data = base64encode(file("${path.module}/Configs/AlpineTests/AlpineScriptTest1/entry.sh"))

  templatedriver = "golang"

  lifecycle {
    ignore_changes        = [name]
    create_before_destroy = true
  }
}
```

### References

https://pkg.go.dev/github.com/docker/docker@v20.10.8+incompatible/api/types/swarm#ConfigSpec
https://docs.docker.com/engine/swarm/configs/#example-use-a-templated-config

* #0000

**Comment by KristianFJones** [comment]
I'd be willing to give this a shot, and submit a PR if the addition is accepted.

**Comment by mavogel** [comment]
@KristianFJones looks good. Feel free to submit a PR
