### ISSUE TITLE
docker_image keep_locally not working as expected

### ISSUE THREAD

**Issue by andyshinn** [kreuzwerker/terraform-provider-docker#27]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
❯ terraform version 
Terraform v0.14.2
+ provider registry.terraform.io/kreuzwerker/docker v2.8.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- docker_image

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.8.0"
    }
  }
}

variable "image" {
  default = "ghcr.io/andyshinn/wbld:latest"
}

variable "github_token" {
  description = "GitHub token for GHCR auth"
}

variable "discord_token" {
  description = "Discord auth token"
}

provider "docker" {
  host = "tcp://localhost:2375"

  registry_auth {
    address  = "ghcr.io"
    username = "andyshinn"
    password = var.github_token
  }
}

resource "docker_container" "wbld" {
  name    = "wbld"
  image   = docker_image.wbld.latest
  command = ["python3", "-m", "wbld.bot"]
  env     = ["DISCORD_TOKEN=${var.discord_token}"]

  volumes {
    volume_name    = "wbld_platformio"
    container_path = "/root/.platformio"
  }

  volumes {
    volume_name    = "wbld_buildcache"
    container_path = "/root/.buildcache"
  }
}

data "docker_registry_image" "wbld" {
  name = var.image
}

resource "docker_image" "wbld" {
  name          = data.docker_registry_image.wbld.name
  pull_triggers = [data.docker_registry_image.wbld.sha256_digest]
  keep_locally  = true
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

https://gist.github.com/andyshinn/2638d4ad091910b55d055b01301bc69a

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
The Docker image should not be removed on Destroy. Since the image is in use by the container it fails tring to remove the image.

### Actual Behavior
The Docker image is being removed even though `keep_locally` is specified.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

Running through GitHub Actions. But tested locally and same behavior occurs.

**Comment by suzuki-shunsuke** [comment]
Thank you for your report.
But I can't reproduce the issue.

```hcl
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.8.0"
    }
  }
}

variable "image" {
  default = "alpine:3.11.6"
}

variable "discord_token" {
  description = "Discord auth token"
}

provider "docker" {
}

resource "docker_container" "wbld" {
  name    = "wbld"
  image   = docker_image.wbld.latest
  command = ["tail", "-f", "/dev/null"]
  env     = ["DISCORD_TOKEN=${var.discord_token}"]

  volumes {
    volume_name    = "wbld_platformio"
    container_path = "/root/.platformio"
  }

  volumes {
    volume_name    = "wbld_buildcache"
    container_path = "/root/.buildcache"
  }
}

data "docker_registry_image" "wbld" {
  name = var.image
}

resource "docker_image" "wbld" {
  name          = data.docker_registry_image.wbld.name
  pull_triggers = [data.docker_registry_image.wbld.sha256_digest]
  keep_locally  = true
}
```

```
$ terraform version
Terraform v0.14.2
+ provider registry.terraform.io/kreuzwerker/docker v2.8.0

$ terraform apply -auto-approve
docker_image.wbld: Creating...
docker_image.wbld: Creation complete after 1s [id=sha256:f70734b6a266dcb5f44c383274821207885b549b75c8e119404917a61335981aalpine:3.11.6]
docker_container.wbld: Creating...
docker_container.wbld: Creation complete after 1s [id=0dc5b981ca697b87e6028a293f9ecd984042c71f7980dd95a6481f7600d656cd]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

$ terraform destroy -auto-approve
docker_container.wbld: Destroying... [id=0dc5b981ca697b87e6028a293f9ecd984042c71f7980dd95a6481f7600d656cd]
docker_container.wbld: Destruction complete after 0s
docker_image.wbld: Destroying... [id=sha256:f70734b6a266dcb5f44c383274821207885b549b75c8e119404917a61335981aalpine:3.11.6]
docker_image.wbld: Destruction complete after 0s

Destroy complete! Resources: 2 destroyed.

$ docker images alpine:3.11.6
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
alpine              3.11.6              f70734b6a266        7 months ago        5.61MB
```

It succeeds to run `terraform destroy` and the Docker image isn't removed.

On the other hand, if `keep_locally` is false, it failed to remove the Docker image, which means the provider tried to remove the Docker image  as expected.

```
$ terraform destroy -auto-approve
docker_container.wbld: Destroying... [id=09682e5ba28f377f25b39ff3e9e99257daa5acf781434a98820e768b83601793]
docker_container.wbld: Destruction complete after 0s
docker_image.wbld: Destroying... [id=sha256:f70734b6a266dcb5f44c383274821207885b549b75c8e119404917a61335981aalpine:3.11.6]

Error: Unable to remove Docker image: Error response from daemon: conflict: unable to delete f70734b6a266 (must be forced) - image is referenced in multiple repositories
```

I checked the source code and it seems that the Docker image isn't removed if `keep_locally` is true.

* https://github.com/kreuzwerker/terraform-provider-docker/blob/b8d28d67e632c476e99786805bb6a56603595ba1/docker/resource_docker_image.go#L12
* https://github.com/kreuzwerker/terraform-provider-docker/blob/b8d28d67e632c476e99786805bb6a56603595ba1/docker/resource_docker_image_funcs.go#L113-L121
* https://github.com/kreuzwerker/terraform-provider-docker/blob/b8d28d67e632c476e99786805bb6a56603595ba1/docker/resource_docker_image_funcs.go#L136-L141

**Comment by andyshinn** [comment]
Thanks. I think the error may actually be elsewhere. Sorry for false alarm.
