### ISSUE TITLE
Plugin versions 2.13 and above not using proxy environment variables for docker image pull from internet

### ISSUE THREAD

**Issue by markhawke7** [kreuzwerker/terraform-provider-docker#276]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

Terraform v1.0.5
on linux_amd64

No plugins are shown as they are pulled and installed at runtime.  See below gists in Debug Output showing version being installed/run and overall results.

Plugin versions tested:
2.12.2
2.13.0
2.14.0
2.15.0
Works - 2.12.2
Fails - 2.13.0 and higher 

### Affected Resource(s)

* `docker_20.10.3`

### Debug Output

Server resides behind a corporate internal network requiring the use of a corportate internet proxy which does not require authentication.  
Environment variables in use at time of running terraform apply:
These have been modified to comply with corporate internet security rules. 
Note I have defined both the upper and lower case versions of the proxy settings as I had found some mention that the uppercase versions were needed by terraform.  This has not been an issue in my experience however I defined them for completeness.:
http_proxy=http://proxywest.???.com:80
ftp_proxy=http://proxywest.???.com:80
HTTPS_PROXY=http://proxywest.???.com:80
https_proxy=http://proxywest.????.com:80
no_proxy=localhost,.fundev.net,.intnet.???.com
NO_PROXY=localhost,.fundev.net,.intnet.???.com
HTTP_PROXY=http://proxywest.???.com:80

Version 2.12.2 Gist Output - Successful run:
https://gist.github.com/markhawke7/68d4b0b3ab3f8f75c609c3008108e81c

Version 2.15.0 - Failed run:
https://gist.github.com/markhawke7/ce1bff583e5d4eafb888c14c98e08bce

### Expected Behaviour

Single docker image is retrieved from a remote/internet site and deployed into docker.  This happens without issue using plugin version 2.12.X.  Plugin version is specified  in driver.versions.tf file.  Here is the contents of the file:

terraform {
  required_version = ">= 0.13"
  required_providers {
    docker = {
      source = "kreuzwerker/docker"
      version = "2.12.2"
    }
  }
}

### Actual Behaviour

With NO changes to the deployment files/configuration other than to the "version" tag in the driver.versions.tf file, the plugin fails to download the docker image as seen in the Version 2.15.0 gist.  Contents of the driver.versions.tf file for this run:

terraform {
  required_version = ">= 0.13"
  required_providers {
    docker = {
      source = "kreuzwerker/docker"
      version = "2.15.0"
    }
  }
}

### Steps to Reproduce

**Success:**
Run using driver.version.tf file specifying 2.12.2 (any version of 2.12)

**Failure**
Run using driver.version.tf file specifying any current version above 2.12.X

As I said, NO other changes are made other than the driver.version.tf file.

This issue has been further verified using the Wireshark network packet sniffer.  The wireshark output clearly shows that with version 2.12.2 the network traffic for the pull of the image is properly making use of the required proxy server and the transfer is occurring without issue from the remote repository.

When a plugin version greater than 2.12.X is used, wireshark output shows connections being attempted directly to the IP address of the remote internet repository.  With NO traffic occurring to/fm the corporate internet proxy, all connections fail and eventually timeout causing the deployment to fail and terminate as shown in the gist.

**Comment by sreedharmanchu** [comment]
Hi,

Even the latest version seems to have this issue.  That is provider doesn't go over corporate proxy and tries to go over internet.
