### ISSUE TITLE
Proposal: Add options for SSH identity file and passphrase to Docker provider

### ISSUE THREAD

**Issue by colinwilson** [kreuzwerker/terraform-provider-docker#29]
### Terraform Version
<code>&#8805; 0.12.25</code>

### Use-cases
The provider has a feature to deploy a docker container using the SSH protocol
```hcl
provider "docker" {
  host = "ssh://user@remote-host:22"
}
```
However there seems to be no explicit way to provide the path to an SSH identity file (private key).
The only implicit workaround seems to be creating an SSH config file on the machine running Terraform to specify the identity file.

### Proposal
Add two options:
```
identity_file
passphrase
```
Use this information in the SSH systemcall.

### References
Issue in archived repo: https://github.com/hashicorp/terraform-provider-docker/issues/268
Related: https://github.com/kreuzwerker/terraform-provider-docker/issues/18

**Comment by rgb000** [comment]
Hello.
Same issue here. Please add possibility to add private key, passphrase.

**Comment by corvint** [comment]
From #101, the proposal:

```hcl
provider "docker" {
  host = "ssh://user@remote-host:22"
  private_key = file(var.my_key_path)
}
```

I believe it is possible to use terraform builtins for the connection as the [`null_resource` provider](https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource) allows for a `connection.private_key` field. There may be other providers that use this pattern, but this is the only example I have offhand.

**Comment by BenNewsome** [comment]
Looks like something about this line needs updating.
https://github.com/kreuzwerker/terraform-provider-docker/blob/8da701db26ba83ab95b6a0abc49b8dc7c6ec778f/docker/config.go#L120

The updated function to enable this appears to have been made here:
https://github.com/docker/cli/blob/d26bdfd4ea235a4e94c5fc907215b197280f80c0/cli/connhelper/connhelper.go#L33

**Comment by mavogel** [comment]
Let's see if we make that with #119

**Comment by aleon1220** [comment]
too much effort to try making it work. The Docker provider needs more work. Refer to https://github.com/kreuzwerker/terraform-provider-docker/issues/80

In my case i was trying to make it work from terraform cloud. It was a pain. Refer to https://discuss.hashicorp.com/t/docker-provider-in-terraform-cloud-error-failed-to-query-available-provider-packages/21148

I will use a combination of 

1. user_data.tpl in my terraform cloud workspace that installs latest docker-compose version up to now 2021-02-22
``` bash
COMPOSE_VERSION="1.28.4"
sudo curl -L "https://github.com/docker/compose/releases/download/$COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```
2.  a docker-compose file embedded in a terraform string variable. See https://gist.github.com/jamesmishra/18ee5d7d053db9958d0e4ccbb37f8e1d

3. finally pray that all of this works and I can restore a PostgreSQL dump from 9.3.3 to RDS PostgreSQL 9.6

**Comment by aleon1220** [comment]
how could we work together to implement this?

**Comment by mavogel** [comment]
feel free to file a PR :) unfortunately we're busy with the refactorings and release this feature as well then

**Comment by AndreiPashkin** [comment]
@corvint 
> I believe it is possible to use terraform builtins for the connection as the [`null_resource` provider](https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource) allows for a `connection.private_key` field. There may be other providers that use this pattern, but this is the only example I have offhand.

As far as my knowledge of Terraform goes the connection directive is only for provisioners, not for resources:
https://www.terraform.io/docs/language/resources/provisioners/connection.html

Another reference:
https://github.com/hashicorp/terraform-plugin-sdk/blob/112e2164c381d80e8ada3170dac9a8a5db01079a/terraform/state.go#L1592

Look at the comment: "ConnInfo is used for the providers to export information which is used to connect to the resource for **provisioning**".

So it's not a pattern for providers, it's a built-in directive for provisioners.

**Comment by sean-nitric** [comment]
@suzuki-shunsuke I'm hoping you can point me in the right direction here.

I am trying to use podman to build my images and its not able to connect to the podman machine on the standard socket

I have tried switching to ssh but the problem is that I must pass the identity file to connect, and the file is not present within the buildx container so I can give a real path to the `-i` argument.

eg.

```terraform
provider "docker" {
  host = "ssh://root@127.0.0.1:60233/run/podman/podman.sock"
  ssh_opts = [
    "-o", "StrictHostKeyChecking=no",
    "-o", "PasswordAuthentication=no",
    "-o", "PubkeyAuthentication=yes",
    "-o", "UserKnownHostsFile=/dev/null",
    "-i", "need a path on the host machine???"  
  ]
}
```
