### ISSUE TITLE
Support for access to insecure http registries

### ISSUE THREAD

**Issue by kriswuollett** [kreuzwerker/terraform-provider-docker#291]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for insecure registries would be very helpful for local development environments like with microk8s out of the box. 

### Potential Terraform Configuration

```hcl
provider "docker" {
  registry_auth {
    # https is implied otherwise
    address = "http://localhost:32000"
  }
}

data "docker_registry_image" "kriswuollett-www" {
  name = "localhost:32000/kriswuollett/www:u-kris-g6fe3acd
}

```

### References

* #135, it was resolved that the reporter was fine with the step of creating a self-signed certificate for the registry and using the `insecure_skip_verify` option. I'd like to avoid needing that step.

**Comment by kriswuollett** [comment]
The error I am currently getting looks like:

`Error: Got error when attempting to fetch image version kriswuollett/www:u-kris-g6fe3acd from registry: Error during registry request: Get "https://localhost:32000/v2/kriswuollett/www/manifests/u-kris-u-kris-g6fe3acd": http: server gave HTTP response to HTTPS client`

**Comment by kriswuollett** [comment]
Currently using this `/etc/docker/daemon.json` and then restarting the service with `sudo service docker restart`:

```
$ cat /etc/docker/daemon.json 
{
  "insecure-registries" : ["localhost:32000"]
}
```

**Comment by kriswuollett** [comment]
Not stale.

**Comment by gaborbalogh1** [comment]
Hi I'm having the same issue any chance on implementing this asap it is currently blocking us from implementing this in our environment.

**Comment by Junkern** [comment]
implement in `v2.20.0`
