### ISSUE TITLE
Support for prevent destruction of docker volumes

### ISSUE THREAD

**Issue by milost** [kreuzwerker/terraform-provider-docker#294]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be very helpful if it was possible to prevent certain volumes from being destroyed during a `terraform destroy`. This way it would be possible, for example, to keep data persisted by a database during the development of the infrastructure (see configuration example below). For example, it would be possible to destroy the actual docker containers and images, but keep any data that is stored in volumes. At a later point in time, an infrastructure could be rebuilt in which, for example, a database has access to the data of a previously created volume.

### New or Affected Resource(s)

* docker_volume

### Potential Terraform Configuration

```hcl
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 2.13.0"
    }
  }
}


resource "docker_image" "postgres" {
  name         = "postgres:${var.server_version}"
  keep_locally = false
}

resource "docker_volume" "postgres" {
  name = var.server_volume
  prevent_destruction = true  # prevent volume from being destroyed
}

resource "docker_container" "postgres" {
  image = docker_image.postgres.name
  name  = var.server_name
  env   = ["POSTGRES_USER=postgres", "POSTGRES_PASSWORD=12345"]
  ports {
    internal = 5432
    external = 5432
  }
  volumes {
    container_path = "/var/lib/postgresql/data"
    volume_name    = var.server_volume
  }
}

```

**Comment by xadlien** [comment]
Would love to see this feature. Please don't close due to being stale. I'll try to make this change myself.

**Comment by xadlien** [comment]
Please assign this to me. I have some working code and am trying to wrap a bow on the commits.

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.
I understand your motivation, but I wonder if we should really add such an attribute.

You can prevent the destruction of resources by running `terraform state rm` before `terraform destroy`.

```console
$ terraform state rm docker_volume.postgres
$ terraform destroy
```

Or

```console
$ terraform state list | grep -E "^docker_volume\." | xargs -n 1 terraform state rm
$ terraform destroy
```

@mavogel What do you think?

**Comment by suzuki-shunsuke** [comment]
Same as Docker Volume, there are many resources which have data and you want to keep.
But they don't have the attribute like `prevent_destroy`.
Then should you add the attribute to those resources?
I don't think so.

So I wonder if adding the attribute to `docker_volume` is a right way.

**Comment by suzuki-shunsuke** [comment]
You can prevent the destruction with [lifecycle.prevent_destroy](https://www.terraform.io/language/meta-arguments/lifecycle#prevent_destroy).
You can remove other resources by excluding Docker Volumes by `terraform state rm`. https://github.com/kreuzwerker/terraform-provider-docker/issues/294#issuecomment-997377040

**Comment by xadlien** [comment]
@suzuki-shunsuke In my experience you almost never want to delete a docker volume. If you run `terraform state rm` on the volume before the destroy, then with the next `terraform apply` it will error saying that the volume already exists. Similarly with using lifecycle.prevent_destroy, it will error out upon destruction. I would love to find a way to define an environment that can be brought up/down without worrying about the volumes and error related to them. Right now the only thing I can think of is having the volumes be a different directory so that they aren't included with the terraform commands on the containers/images.

**Comment by xadlien** [comment]
If the verbiage is the issue, we can change `prevent_destroy` to be `ephemeral` with a default value of true so it would maintain backwards compatibility.

**Comment by suzuki-shunsuke** [comment]
Thank you for your explanation.
I see.

> Right now the only thing I can think of is having the volumes be a different directory so that they aren't included with the terraform commands on the containers/images.

As you said, managing the volume outside Terraform is one of the solution.

I guess the resource is removed by `terraform destroy` even if the method `resourceDockerVolumeDelete` returns nil immediately, so it's difficult to keep the resource in state.
https://github.com/kreuzwerker/terraform-provider-docker/pull/326#discussion_r771776036
