### ISSUE TITLE
Unsupported block type build on docker_image

### ISSUE THREAD

**Issue by pedrocesar-ti** [kreuzwerker/terraform-provider-docker#31]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.24
+ provider.docker v2.7.2

### Affected Resource(s)
Please list the resources as a list, for example:
- docker_image

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "docker_image" "app" {
  name = "appondocker"
  build {
    path = "."
  }
}
```

### Expected Behavior
Build a local Dockerfile.

### Actual Behavior
```
Error: Unsupported block type

  on myfirstdocker.tf line 17, in resource "docker_image" "app":
  17:   build {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Have any Dockerfile
2. Create a .tf file and try to build it using the Docker Provider.
3. `terraform plan`

**Comment by suzuki-shunsuke** [comment]
Please use the latest version [v2.8.0](https://github.com/kreuzwerker/terraform-provider-docker/releases/tag/v2.8.0).
The problem doesn't occur.

main.tf

```hcl
resource "docker_image" "app" {
  name = "appondocker"
  build {
    path = "."
  }
}
```

versions.tf

```hcl
terraform {
  required_providers {
    docker = {
      source = "kreuzwerker/docker"
    }
  }
  required_version = ">= 0.13"
}
```

```
$ terraform version
Terraform v0.13.5
+ provider registry.terraform.io/kreuzwerker/docker v2.8.0

$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # docker_image.app will be created
  + resource "docker_image" "app" {
      + id     = (known after apply)
      + latest = (known after apply)
      + name   = "appondocker"
      + output = (known after apply)

      + build {
          + dockerfile = "Dockerfile"
          + path       = "."
          + remove     = true
          + tag        = []
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```
