### ISSUE TITLE
Attaching existing internal network to container forces it to be recreated every time

### ISSUE THREAD

**Issue by deespater** [kreuzwerker/terraform-provider-docker#319]
**UPD 2021-11-30: This bug applies only to networks marked as `internal`**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version
```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/kreuzwerker/docker v2.15.0
```

### Affected Resource(s)
* `docker_container`

### Terraform Configuration Files

```hcl
resource "docker_network" "internal" {
  name = "my_internal"
  internal = true
}

resource "docker_image" "image" {
  name = "mysql:8"
}

resource "docker_container" "container" {
  name = "mysql"
  image = docker_image.image.latest
  env = ["MYSQL_ROOT_PASSWORD=password"]

  ports {
    external = 3306
    internal = 3306
  }

  networks_advanced {
    name = docker_network.internal.name
  }
}
```

### Debug Output
https://gist.github.com/deespater/1e71a11bce2999abeadb831ea8a5317c

### Expected Behaviour
Container should not be recreated since nothing has changed in tf file nor on docker side.

### Actual Behaviour
If `docker_container` has existing **internal** network attached via `network_advanced` it will be recreated each time disregarding any changes.
```
+ ports { # forces replacement
     + external = 3306 # forces replacement
     + internal = 3306 # forces replacement
     + ip       = "0.0.0.0" # forces replacement
     + protocol = "tcp" # forces replacement
}
```

#### Steps to reproduce

1. Use provided TF file
2. Run `terraform apply` with correct docker host (mine was via ssh)
3. See that terraform will create `docker_network`, `docker_image` and `docker_container` using mentioned image and network
4. Check container is created and in fact uses image and network
5. Do not change anything
6. Run `terraform apply` again
7. See terraform will recreate container because `ports` are **forcing replacement**
8. Let terraform recreate container
9. Go to step 6

### Important Factoids

- Docker version 20.10.3, build b455053
- Docker provider uses docker connection via `ssh`
- if `docker_container` does not have network defined in `network_advanced` no issue is observed
- if `docker_network` is not defined as `internal = true` no issue is observed

**Comment by alexkunin** [comment]
I had similar issue, and it turned out that using network name instead of ID might cause unnecessary updates. The following seems to be the correct way of doing it (at least it was in my case, with previous versions of this provider and Terraform):

```hcl
networks_advanced {
  name = docker_network.internal.id
}
```
