### ISSUE TITLE
provider compares sub-image digest against repo digest

### ISSUE THREAD

**Issue by kdomanski** [kreuzwerker/terraform-provider-docker#328]
I"m trying to deploy a prometheus container on an ARM machine. The prometheus image is a multi-arch image, which means that it has a different digest for the multi-arch image as a whole, and a different digest for each per-arch sub-image.

For example, at the time of writing the `prom/prometheus:latest` image resolves to:
- For the whole image: `sha256:cb9817249c346d6cfadebe383ed3b3cd4c540f623db40c4ca00da2ada45259bb`
- For AMD64 sub-image: `sha256:a3d385fc29f926eed67f0d60ffaf72d199f3f9c24af5d55cd1802f2dc1dc9b4b`
- For ARM sub-image: `sha256:26e3dea0ba4c619d19d82910fdfa1ea050b5eebb69fbe05f2763b549742ab7bf`

The running container has the arch-specific sub-image digest in its `.Image` field and the whole image digest in `.Config.Image`. Then preparing a plan, this provider compares the sub-image digest from existing image to the whole-image digest from image manifest, which means that they will never match and the provider will always force container re-creation.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

On my workstation:
```
Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/kreuzwerker/docker v2.15.0
```

On target machine:
```
Client:
 Version:           20.10.7-qnap3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        50b64c4
 Built:             Tue Oct 26 07:03:56 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7-qnap3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f180ce8
  Built:            Tue Oct 26 06:21:14 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Affected Resource(s)

* `docker_image`
* `docker_container`

### Terraform Configuration Files

```
terraform {
    required_providers {
        docker = {
            source  = "kreuzwerker/docker"
            version = "~> 2.15"
        }
    }

    backend "s3" {
        bucket = "XXX"
        key = "XXX"
        region = "XXX"
        profile = "XXX"
    }
}

provider "docker" {
    host = "ssh://"
}

resource "docker_network" "homestack" {
  name = "homestack"
}

data "docker_image" "prometheus" {
  name = "prom/prometheus:latest"
}

resource "docker_container" "prometheus" {
    name = "prometheus"
    image = data.docker_image.prometheus.repo_digest
    volumes {
        container_path = "/prometheus"
        volume_name = docker_volume.prometheus.name
        read_only = false
    }

    networks_advanced {
        name = docker_network.homestack.name
    }

    lifecycle {
        ignore_changes = [
            healthcheck,
            ulimit
        ]
    }
}
```
### Expected Behaviour

No change to the existing container.

### Actual Behaviour

`image             = "sha256:26e3dea0ba4c619d19d82910fdfa1ea050b5eebb69fbe05f2763b549742ab7bf" -> "prom/prometheus@sha256:cb9817249c346d6cfadebe383ed3b3cd4c540f623db40c4ca00da2ada45259bb" # forces replacement`

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Running from a normal laptop over SSH againt an ARM machine

**Comment by kdomanski** [comment]
Nevermind, I've been using `repo_digest` instead of `id`.

**Comment by sveba** [comment]
I have the same problem. I'm running from ARM-MacBook against amd64 machine.

@kdomanski  What do you mean by: I used `repo_digest` instead of `id`?
If I put `image.id` I get an ERROR from the docker daemon, that it can not find this Image

Can you please post your current HCL
