### ISSUE TITLE
Support for isolation in docker_container

### ISSUE THREAD

**Issue by nmohammadi** [kreuzwerker/terraform-provider-docker#329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://github.com/kreuzwerker/terraform-provider-docker/issues/329#issuecomment-1001952350

The problem is when creating a container in windows you can select a container isolation technology like hyperv
but docker_container does not support it.
It is very important because you can not run older windows images on a newer windows version without hyperv isolation.

### New or Affected Resource(s)

* docker_container

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by suzuki-shunsuke** [comment]
Please write the description.
What's the problem?

**Comment by nmohammadi** [comment]
The problem is when creating a container in windows you can select a
container isolation technology like hyperv but docker_container does
not support it.
It is very important because you can not run older windows images on a
newer windows version without hyperv isolation.

**Comment by suzuki-shunsuke** [comment]
Thank you for your explanation.
I understood. I updated the description. https://github.com/kreuzwerker/terraform-provider-docker/issues/329#issue-1089673711
I'm sorry but I don't know Windows well.
Would you tell us how to support?
Do we have to add some option to `docker_container`?
Please update `Potential Terraform Configuration` if you have any idea.
Please tell us the reference related to this issue if you know.
