### ISSUE TITLE
File mode null when using docker_registry_image build

### ISSUE THREAD

**Issue by joraff** [kreuzwerker/terraform-provider-docker#333]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

Terraform v1.1.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azurerm v2.90.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/kreuzwerker/docker v2.15.0

### Affected Resource(s)

* `docker_registry_image`

### Terraform Configuration Files

```hcl

terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.15.0"
    }
  }
}

provider "docker" {
  host = "unix:///var/run/docker.sock"

  registry_auth {
    address  = "mycontainerregistry.io"
    username = "myusername"
    password = "mypassword"
  }
}

resource "null_resource" "git_clone_github_backup_utils" {
  provisioner "local-exec" {
    command = "rm -rf github-backup-utils && git clone git@github.com:github/backup-utils.git github-backup-utils && cd github-backup-utils && git checkout v3.3.1"
  }
}

resource "docker_registry_image" "backup_utils" {
  name = "mycontainerregistry.io/github_backup_utils:v3.3.1"

  build {
    context = "${path.cwd}/github-backup-utils"
  }

  depends_on = [
    null_resource.git_clone_github_backup_utils
  ]
}
```

### Debug Output

Will provide if needed, I don't think it's relevant here.

### Expected Behaviour

Files copied into the container should retain their file modes.

### Actual Behaviour

```
$ docker run --rm -it mycontainerregistry.io/github_backup_utils:v3.3.1 ls -la
total 100
drwxr-xr-x 1 root root 4096 Jan  5 23:08 .
drwxr-xr-x 1 root root 4096 Jan  5 23:10 ..
---------- 1 root root   41 Jan  1  1970 .dockerignore
d--------- 7 root root 4096 Jan  1  1970 .git
---------- 1 root root   72 Jan  1  1970 .gitattributes
d--------- 3 root root 4096 Jan  1  1970 .github
---------- 1 root root   27 Jan  1  1970 .gitignore
---------- 1 root root    6 Jan  1  1970 .ruby-version
---------- 1 root root  775 Jan  1  1970 CONTRIBUTING.md
---------- 1 root root  442 Jan  1  1970 Dockerfile
---------- 1 root root  382 Jan  1  1970 Dockerfile.alpine
---------- 1 root root 1055 Jan  1  1970 LICENSE
---------- 1 root root  484 Jan  1  1970 Makefile
---------- 1 root root 2839 Jan  1  1970 README.md
---------- 1 root root 4335 Jan  1  1970 RELEASING.md
---------- 1 root root 4637 Jan  1  1970 STYLEGUIDE.md
---------- 1 root root 3584 Jan  1  1970 backup.config-example
d--------- 2 root root 4096 Jan  1  1970 bin
d--------- 3 root root 4096 Jan  1  1970 debian
d--------- 2 root root 4096 Jan  1  1970 docs
d--------- 2 root root 4096 Jan  1  1970 script
d--------- 1 root root 4096 Jan  1  1970 share
d--------- 3 root root 4096 Jan  1  1970 test
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

A `docker build ...` using the same context produces an image with the file modes intact.

Further, an image built with `docker_image` does not have this issue, but I need the additional arguments in `docker_registry_image` (specifically, platform).

**Comment by Junkern** [comment]
@joraff This is fixed with the current release
