### ISSUE TITLE
docker_service log_driver docs have invalid options example

### ISSUE THREAD

**Issue by alexkunin** [kreuzwerker/terraform-provider-docker#336]
Currently [docs](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/service#nested-schema-for-task_speclog_driver) have this snippet:
```
log_driver {
  name = "json-file"

  options {
    max-size = "10m"
    max-file = "3"
  }
}
```
But the correct way of doing that looks like this (note `=`):
```
log_driver {
  name = "json-file"

  options = {
    max-size = "10m"
    max-file = "3"
  }
}
```
I'll try to prepare a PR when I have free time, but if anyone can do this quickly, please go ahead.

**Comment by mavogel** [comment]
fixed by #337
