### ISSUE TITLE
with version 2.16.0 terraform apply errors when rm is set to true

### ISSUE THREAD

**Issue by pmoosh** [kreuzwerker/terraform-provider-docker#339]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Using the example from the documentation terraform apply will error out, unless a sleep (or any command) is added

### Affected Resource(s)

* `docker_container`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    docker = {
      source = "kreuzwerker/docker"
      version = "2.16.0"
    }
  }
}

provider "docker" {
  # Configuration options
}

resource "docker_image" "ubuntu" {
  name = "ubuntu:precise"
}

resource "docker_container" "ubuntu" {
  name  = "foo"
  image = docker_image.ubuntu.latest
  rm = true
#   command = ["sleep", "1"]
}
```

### Debug Output

Plan: 2 to add, 0 to change, 0 to destroy.
docker_image.ubuntu: Creating...
docker_image.ubuntu: Creation complete after 6s [id=sha256:5b117edd0b767986092e9f721ba2364951b0a271f53f1f41aff9dd1861c2d4feubuntu:precise]
docker_container.ubuntu: Creating...
╷
│ Error: Error: No such container: af79567db7b9c5fb588427f146f9a0c17a63bc8d317e74330bbc673b9f8a7f44
│ 
│   with docker_container.ubuntu,
│   on test.tf line 18, in resource "docker_container" "ubuntu":
│   18: resource "docker_container" "ubuntu" {
│ 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by suzuki-shunsuke** [comment]
I could reproduce the issue.

```
2022-01-25T14:27:17.908+0900 [INFO]  provider.terraform-provider-docker_v2.16.0: 2022/01/25 14:27:17 [DEBUG] found local image via imageName: sha256:5b117edd0b767986092e9f721ba2364951b0a271f53f1f41aff9dd1861c2d4fe: timestamp=2022-01-25T14:27:17.908+0900
2022-01-25T14:27:18.180+0900 [INFO]  provider.terraform-provider-docker_v2.16.0: 2022/01/25 14:27:18 [INFO] Waiting for container: '44892a91283bf11b3ad352f9d35665a1b92d43add7c6a5aaca0ff505552acf5e' to run: max '15s seconds': timestamp=2022-01-25T14:27:18.180+0900
2022-01-25T14:27:18.200+0900 [INFO]  provider.terraform-provider-docker_v2.16.0: 2022/01/25 14:27:18 [DEBUG] Waiting for state to become: [running]: timestamp=2022-01-25T14:27:18.200+0900
2022-01-25T14:27:18.329+0900 [ERROR] vertex "docker_container.ubuntu" error: Error: No such container: 44892a91283bf11b3ad352f9d35665a1b92d43add7c6a5aaca0ff505552acf5e
╷
│ Error: Error: No such container: 44892a91283bf11b3ad352f9d35665a1b92d43add7c6a5aaca0ff505552acf5e
│ 
│   with docker_container.ubuntu,
│   on main.tf line 17, in resource "docker_container" "ubuntu":
│   17: resource "docker_container" "ubuntu" {
│ 
╵
```

And I could solve the problem by specifying `command = ["tail", "-f", "/dev/null"]`

```tf
resource "docker_container" "ubuntu" {
  name    = "foo"
  image   = docker_image.ubuntu.latest
  rm      = true
  command = ["tail", "-f", "/dev/null"]
}
```

```tf
resource "docker_container" "ubuntu" {
  name  = "foo"
  image = docker_image.ubuntu.latest
  rm = true
#   command = ["sleep", "1"]
}
```

If the Docker image `ubuntu` is used and `command` isn't specified, the container exits immediately, and by `rm` option the container is removed.

To keep the container running, `command` should be specified in case of `ubuntu`.

**Comment by suzuki-shunsuke** [comment]
We should update the example.
https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container
