### ISSUE TITLE
https://docs.docker.com/engine/api/v1.41/ isn't implemented, so you can't pass cap_add to a service

### ISSUE THREAD

**Issue by brandonros** [kreuzwerker/terraform-provider-docker#34]
https://github.com/dperson/openvpn-client/blob/master/docker-compose.yml#L7 example

**Comment by mavogel** [comment]
This would imply to update to Docker `20.10` for the API version `1.41` -> https://docs.docker.com/engine/api/#api-version-matrix

**Comment by mavogel** [comment]
closed in favor of #142 . Will be implemented there.
