### ISSUE TITLE
log_opts causing continuous container recreation

### ISSUE THREAD

**Issue by stephenliberty** [kreuzwerker/terraform-provider-docker#340]
With the new version 2.16.0, the "log_driver" does indeed default to whatever the system has set, rather than being hard-coded to default to `json-file`. However, there was an accidental/surprise result of this change. 

In a system where the /etc/docker/daemon.json is set to, for example:

```json
    {
        "log-driver": "fluentd",
        "log-opts": {
        "fluentd-address": "localhost:24226",
        "fluentd-async": "true"
        }
      }
```

There are two "log-opts" that are set along with the different log driver. When the terraform provider runs, the log_driver is set to the computed value of "fluentd" for the container. The log_opts are also filled in. BUT because log_opts aren't set as a potentially computed value, every time we re-run `terraform plan`, terraform thinks we're trying to null out the log_opts so it recreates the container. As an example, this was grabbed from a plan output showing the problem:

```
~ log_driver        = "fluentd" -> (known after apply)
- log_opts          = {
  - "fluentd-address" = "localhost:24226"
  - "fluentd-async"   = "true"
 } -> null # forces replacement
```

The previous run had no mention of log_opts in the plan.

**Comment by suzuki-shunsuke** [comment]
ref. https://github.com/kreuzwerker/terraform-provider-docker/pull/270#issuecomment-1021052259

**Comment by suzuki-shunsuke** [comment]
📝 

https://github.com/kreuzwerker/terraform-provider-docker/blob/a8517ea3024f681baa609e930120482d09900733/internal/provider/resource_docker_container.go#L717-L722

**Comment by suzuki-shunsuke** [comment]
Hmm...
Maybe log_opts should be `Computed: true`.

**Comment by stephenliberty** [comment]
I'm pretty sure that would fix stuff, but I'm unfortunately in no position right now to try and make the change and test it :\

**Comment by suzuki-shunsuke** [comment]
I've created a pull request although I don't test yet.
https://github.com/kreuzwerker/terraform-provider-docker/pull/342
