### ISSUE TITLE
Support for [docker_container example using docker_image.repo_digest as docker_image.latest is deprecated ]

### ISSUE THREAD

**Issue by darren-rose** [kreuzwerker/terraform-provider-docker#347]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Update docker_container example to use docker_image. repo_digest as repo_digest.latest is deprecated

### New or Affected Resource(s)

* docker_container

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by VergeDX** [comment]
I also found there is no deprecated warning when I tried the README's demo.
Either `terraform validate` or `terraform apply` gives me normal output...
