### ISSUE TITLE
ECR, Got error getting registry image digest: Got bad response from registry: 405 Method Not Allowed

### ISSUE THREAD

**Issue by michaelhelmick** [kreuzwerker/terraform-provider-docker#358]
I'm not sure this is so much a bug of this provider that it is a change to AWS ECR image apis. Creating this ticket to track in case anybody else comes across the problem.

https://github.com/kreuzwerker/terraform-provider-docker/blob/master/internal/provider/resource_docker_registry_image_funcs.go#L470 calls `DELETE` on the image manifest.

In us-west-2, this is causing a 405 Method Not Allowed; and the linked line of code is where I narrowed down this error can be raised from. (The other line is an info log, but the `deleteDockerRegistryImage` uses `diag.Error`

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

```
Terraform v1.0.3
+ provider registry.terraform.io/hashicorp/aws v3.74.3
+ provider registry.terraform.io/hashicorp/external v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/kreuzwerker/docker v2.16.0
```

### Affected Resource(s)

- `docker_registry_image`

### Terraform Configuration Files

For client privacy, I can't paste the configuration; however, this is using the https://registry.terraform.io/modules/terraform-aws-modules/lambda/aws/latest (`docker-build` under the hood) module that uses this provider. There are also some docker images not using the lambda one and using the provider directly.

### Debug Output

For client privacy, I can't paste the configuration.

### Expected Behavior

This has been working since we've been using this provider and stopped working two days ago.
Behavior still works in us-east-1.

### Actual Behavior

Deleting the registry image returns a 405 method not allowed.

### Steps to Reproduce

1. Use the module as expected, `terraform apply`
2. Make changes to the image and `terraform apply` again
3. Again, this works in us-east-1 but fails in us-west-2.

### Important Factoids

The following code should return a 405 in us-west-2, but succeed in us-east-1:

```
TOKEN=$(aws ecr get-authorization-token --output text --query 'authorizationData[].authorizationToken')
curl -i -H "Authorization: Basic $TOKEN" -X "DELETE" https://<account-id>.dkr.ecr.us-west-2.amazonaws.com/v2/<repo-name>/manifests/<sha256:digest>
```

~~Filing a support issue with AWS to determine if this is a bad deploy on their part or a API that's being deprecated.~~
> just got word from aws that they are updating internal library for ecr which is causing it, us-west-2 was done n they are doing us-east-1

**Comment by michaelhelmick** [comment]
Prior, `DELETE` from ecr would return a 404 which Terraform would swallow; it now returns 405 and raises an error.

**Comment by blakecannon-projectcanary** [comment]
I'm having this issue with us-east-2 starting yesterday but everything is working just fine in us-west-2. I had to add a lifecycle rule to my docker_registry_image to build the image and update the task_def but the codebuild still gets exit status 1 and technically fails.

**Comment by michaelhelmick** [comment]
@blakecannon-projectcanary looks like if you're using `docker_registry_image` you can pass `keep_remotely = true` and it will bypass the delete.

**Comment by BradyShober** [comment]
We also are experiencing this in us-east-2. On our support case with AWS they have stated that the ECR team will be reverting the change causing this issue.

**Comment by michaelhelmick** [comment]
> We also are experiencing this in us-east-2. On our support case with AWS they have stated that the ECR team will be reverting the change causing this issue.

Can confirm!

**Comment by Junkern** [comment]
Is this still an issue? I have been playing around a bit with the provider and ECR registry and did not come across any `405` issues.

The last comment also suggests, that this was an unintented change by AWS which got reverted?

**Comment by Junkern** [comment]
We are totally on the same page here, such cases can definitely handled be better in the provider. 
As we have to catch up on many issues and this `405` response is not a problem for now, I will close this ticket.
But it is definitely on the roadmap to improve the registry authentication handling.
