### ISSUE TITLE
404 Page not found 

### ISSUE THREAD

**Issue by abarberenaCPDS** [kreuzwerker/terraform-provider-docker#361]
#### Broken Link

On https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container.html#import

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/43246964/159175280-2ac2dbd6-72f7-4f16-a878-c2d16c33e2e2.png">

**Comment by suzuki-shunsuke** [comment]
URL is wrong.
The correct URL is https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#import
Please send a pull request if URL is wrong in the document.

**Comment by abarberenaCPDS** [comment]
Please close, this has been reported and addressed by the HC Team.

Ref: (https://discuss.hashicorp.com/t/broken-link-404/37412/2)[https://discuss.hashicorp.com/t/broken-link-404/37412/2]

**Comment by suzuki-shunsuke** [comment]
https://discuss.hashicorp.com/t/broken-link-404/37412/4
