### ISSUE TITLE
File owner, group and mode

### ISSUE THREAD

**Issue by alejandrocgf** [kreuzwerker/terraform-provider-docker#368]
Is it possible to change the owner, the group and the mode of uploaded files?

When I execute the ‘docker cp’ command I always pipe source files with ‘tar’ changing the owner, the group and the mode. Is it possible to do something similar with terraform?

**Comment by Junkern** [comment]
To understand you correctly: You want to have an equivalent to the `docker cp` command in this terraform provider?
Sadly, this is currently not supported and 99% won't be in the future.

You can ofc change file owner, group and mode when you `COPY` files in the Dockerfile, but that is probably not the solution you are looking for.
