### ISSUE TITLE
Unable to inspect volume: Error: No such volume: docuum-data

### ISSUE THREAD

**Issue by viceice** [kreuzwerker/terraform-provider-docker#374]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

```
Terraform v1.1.9
on windows_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/helm v2.5.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.10.0
+ provider registry.terraform.io/hashicorp/random v3.1.3
+ provider registry.terraform.io/kreuzwerker/docker v2.16.0
``` 

### Affected Resource(s)

* `docker_volume`

### Terraform Configuration Files

```hcl
resource "docker_volume" "docuum_data" {
  name = "docuum-data"
}
```

### Expected Behaviour

Terraform should recreate the missing volume, but currently it fails. The volume was accidently deleted while resetting the docker storage.

### Actual Behaviour

```
module.devel.module.drone.kubernetes_daemonset.drone_runner: Refreshing state... [id=docker-drone/drone-runner]
╷
│ Error: Unable to inspect volume: Error: No such volume: docuum-data
│ 
│   with module.app02.docker_volume.docuum_data,
│   on modules/docker-dev-windows/docuum.tf line 32, in resource "docker_volume" "docuum_data":
│   32: resource "docker_volume" "docuum_data" {
│ 
╵
Error: Process completed with exit code 1.
```

### Steps to Reproduce

1. `terraform apply`
2. manually delete the volume
3. `terraform plan`

**Comment by viceice** [comment]
fixed it via manual deleting state with `terraform state rm module.app02` , that module contains the missing resources.

**Comment by Junkern** [comment]
Closing because it is fixed.

**Comment by gchait** [comment]
How is `state rm` a fix?
