### ISSUE TITLE
Support for `docker stack` resource

### ISSUE THREAD

**Issue by mulder999** [kreuzwerker/terraform-provider-docker#376]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be super fun to also include support for [`docker stack`](https://docs.docker.com/engine/reference/commandline/stack/) as a resource.

### New or Affected Resource(s)

* New docker_stack resource managing lifecycle using `docker stack deploy` and `docker stack rm`

**Comment by juvenn** [comment]
In docker's parlance, docker stack is not a resource at all, but **manages** resources defined in docker-compose.yml. All resources are defined in compose file. And all resource kinds are supported by this provider already. So there's no need to support docker stack. Use `terraform plan/apply` instead.

That's to say,
* Firstly, translate docker-compose.yml into `*.tf` resource definitions;
* then, use `terraform plan/apply` to deploy resources.

**Comment by tafaust** [comment]
@Junkern I think the "new resource" label can be dropped according to @juvenn's findings. 
However, I still wonder how to group resources (for example a backend service, container with database service, container) in a stack when using this terraform provider?
Grouping the resources in a stack makes it easier to manage the resources in swarmpit or portainer.

**Comment by tafaust** [comment]
I just saw in my portainer that docker stack seems to apply labels with key `com.docker.stack.namespace` to its resources to group them into a stack with the `value`. I still need to test it but that solves this issue pretty much.

**Comment by tafaust** [comment]
FYI @mulder999 

@suzuki-shunsuke I think this issue can be closed. A `com.docker.stack.namespace` label is the solution and the resource contain a `label` block. Example:

```
resource "docker_service" "foo" {

  ...

  label {
    name  = "com.docker.stack.namespace"
    value = "my-stack" 
  }

  ...

}
```

**Comment by mulder999** [comment]
Thanks for feedback. I have some doubts it would be enough. How would you handle overlay networks?

**Comment by mulder999** [comment]
Thanks, for the extra details, it looks great.
