### ISSUE TITLE
chore(ci): replace diff checker for the docs

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#383]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Replace the diff check action for the docs. See [here](https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.github/workflows/test.yml#L44)

### New or Affected Resource(s)

* docker_all

**Comment by Junkern** [comment]
@mavogel what exactly is the plan for this issue? Replace the `git diff` with a specific tool you have in mind?

**Comment by Junkern** [comment]
updated the link to: https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.github/workflows/test.yml#L44
