### ISSUE TITLE
feat: update to terraform-plugin-sdk2

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#4]
- see https://github.com/terraform-providers/terraform-provider-docker/pull/310
- https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html

**Comment by mavogel** [comment]
Currently, trying to fix
```sh
tf-sdk-migrator v2upgrade --sdk-version v2.4.0
Rewriting provider go.mod file...
Rewriting SDK package imports...
Running `go mod tidy`...
Error running go mod tidy: exit status 1
go: github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.0 requires
        cloud.google.com/go@v0.61.0 requires
        github.com/google/martian/v3@v3.0.0 requires
        golang.org/x/net@v0.0.0-20190628185345-da137c7871d7/go.mod: verifying module: golang.org/x/net@v0.0.0-20190628185345-da137c7871d7/go.mod: cannot authenticate record data in server response
```

**Comment by innovate-invent** [comment]
I did not, it looks like the hash of the module is not matching what it is expecting.
I should point out that in my PR I have many manual changes that are required for the update.

**Comment by mavogel** [comment]
Ok thanks for the heads-up. Do you need any support on the PR from my side? I'd like to push this one forward :)

**Comment by innovate-invent** [comment]
Do you mind taking over the PR? It looks like the original repo and yours have diverged a bit

**Comment by mavogel** [comment]
Sure thing. I'll push it over here to this repo then. Thanks for the initial work

**Comment by innovate-invent** [comment]
try and delete the go.sum file?

**Comment by mavogel** [comment]
tried deleting `go.sum`, but it did not help 😕 

- I had a similar issue with `golang.org/x/oauth2` which I could solve with `go get golang.org/x/oauth2@v0.0.0-20190604053449-0f29369cfe45`, but for `golang.org/x/net` it does not work...
- I also tried `export GOPROXY=https://gocenter.io,https://proxy.golang.org,direct`, which did not help either

**Comment by innovate-invent** [comment]
perhaps add 
```
replace github.com/google/martian/v3@v3.0.0 => github.com/google/martian/v3@v3.1.0
```

to your go.mod?

**Comment by mavogel** [comment]
`go clean -modcache` was the key :) Thx. Now I can continue
