### ISSUE TITLE
ci: evaluate helper bots

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#41]
Benefit: to keep the repository and issues clean we could use the help of server bots like [goreleaser](https://github.com/goreleaser/goreleaser/tree/master/.github) does
- [ ] kodiak
- [x] dependency update bot -> renovate #162 
- [x] stale

**Comment by mavogel** [comment]
@suzuki-shunsuke do you think we need https://kodiakhq.com/#why ? I'd say we leave it out for the moment and review helpers later, when we got `3.0.0` out. WDYT? Feel free to close then

**Comment by suzuki-shunsuke** [comment]
I think `kodiak` isn't needed for us now.
