### ISSUE TITLE
Support for passing flags to an image

### ISSUE THREAD

**Issue by matifali** [kreuzwerker/terraform-provider-docker#413]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please allow passing flags to images. For example, the `mathworks/matlab` image accepts `-vnc` flag to start a vnc server.

```
docker run -it --rm -p 5901:5901 -p 6080:6080 mathworks/matlab -vnc
```

**Comment by matifali** [comment]
This is not a command but. It's a command line argument. 
Using your suggestion it doesn't work.

**Comment by Junkern** [comment]
The `mathworks/matlab` docker does have an [`ENTRYPOINT` directive](https://hub.docker.com/layers/matlab/mathworks/matlab/latest/images/sha256-44d8614e3a46b36b48b3c64b86710515a1a43f1fbd4d295750e92fbe6fe35920?context=explore)
That means, that anything you pass as a "command" (either with the docker cli or with this provider) will be added as an parameter to the entrypoint. `docker run -it --rm -p 5901:5901 -p 6080:6080 mathworks/matlab -vnc` will essentially execute a  `/bin/run.sh -vnc`.
Here a better explanation: https://phoenixnap.com/kb/docker-cmd-vs-entrypoint

What you are missing (and what I did not include in my example)  are the other `docker run` options (`--rm`, `-it`, `-p`):

-   [`-p`](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#ports)
-   [`-it`](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#tty)

**Comment by matifali** [comment]
How may I pass the other required options using terraform?

**Comment by Junkern** [comment]
What exactly do you mean with "other required options"? In case you mean the `--rm`, there is an [attribute for that](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#rm)

**Comment by matifali** [comment]
> What exactly do you mean with "other required options"? In case you mean the `--rm`, there is an [attribute for that](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#rm)

##VNC
```
# VNC
resource "coder_app" "novnc" {
  agent_id = coder_agent.dev.id
  name     = "noVNC"
  url      = "http://localhost:6080"
  icon     = "https://ppswi.us/noVNC/app/images/icons/novnc-icon.svg"
}
```
##`docker_container`

```
resource "docker_container" "workspace" {
  count = data.coder_workspace.me.start_count
  image = docker_image.coder_image.latest
  cpu_shares = var.cpu
  memory = "${var.ram*1024}"
  # Uses lower() to avoid Docker restriction on container names.
  name = "coder-${data.coder_workspace.me.owner}-${lower(data.coder_workspace.me.name)}"
  # Hostname makes the shell more user friendly: coder@my-workspace:~$
  hostname = lower(data.coder_workspace.me.name)
  dns      = ["1.1.1.1"]
  # Use the docker gateway if the access URL is 127.0.0.1 
  entrypoint = ["sh", "-c", replace(coder_agent.dev.init_script, "127.0.0.1", "host.docker.internal")]
  
  # MATLAB Specfic argumnets
  stdin_open = true
  tty = true
  ports {
  	internal = 5901
  	external = 5901
  }
  ports {
  	internal = 6080
  	external = 6080
  }
  command = ["/bin/run.sh", "-vnc"]

  env = ["CODER_AGENT_TOKEN=${coder_agent.dev.token}"]
  host {
    host = "host.docker.internal"
    ip   = "host-gateway"
  }
  volumes {
    container_path = "/home/matlab/"
    volume_name    = docker_volume.home_volume.name
    read_only      = false
  }
}
```
This is my current configuration and still vnc is not accessable.

**Comment by Junkern** [comment]
This is not an issue with this provider, we are mostly simply wrapping the docker cli. 
Providing the same entrypoint and command values to the `docker run` command also does not work (please see https://stackoverflow.com/questions/47648775/docker-entrypoint-and-cmd-together)
If you want to run multiple different binary as entrypoint or command, you have to combine them in a single bash script.
