### ISSUE TITLE
Support for passing arguments to the container's entrypoint

### ISSUE THREAD

**Issue by phorcys420** [kreuzwerker/terraform-provider-docker#415]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A way to pass arguments to the entrypoint like with ``docker run`` without having to specify the entrypoint.
e.g the ``-vnc`` argument in ``docker run -it --rm -p 5901:5901 -p 6080:6080 mathworks/matlab -vnc``

### New or Affected Resource(s)

* docker_container

### Potential Terraform Configuration

```hcl
resource "docker_container" "foo" {
  image = "mathworks/matlab:latest"
  name  = "foo"
  args = ["-vnc"] # if you already defined an entrypoint, then it would append to that one instead
}
```

### References

* #0000

**Comment by matifali** [comment]
Related to #413 but more elaborated.

**Comment by Junkern** [comment]
Sorry to be nitpicky here, but as I said in #413 this is already possible.
```
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.19.0"
    }
  }
}

resource "docker_image" "base" {
  name         = "mathworks/matlab"
  keep_locally = true
}

resource "docker_container" "base" {
  name    = "test"
  image   = docker_image.base.latest
  command = ["-vnc"]

  ports {
  	internal = 5901
  	external = 5901
  }
  ports {
  	internal = 6080
  	external = 6080
  }
}
```
After running `terraform apply`, I open `localhost:6080` and can see the mathworks UI.

Looking at the code from the other issue, maybe this will help you: https://stackoverflow.com/questions/47648775/docker-entrypoint-and-cmd-together.

**Comment by phorcys420** [comment]
Alright, I didn't have a look at #413, didn't know ``command`` existed as I saw it nowhere in the provider docs.
:+1:

**Comment by Junkern** [comment]
Ah, I think I combined the answer to both you and @matifali because you had the same question and using the same image.
The `command` option is actually the third in the optional block: https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container

**Comment by matifali** [comment]
> Alright, I didn't have a look at #413, didn't know ``command`` existed as I didn't see it in the provider docs.
> :+1:

But in our case. `coder` is overwriting the `entrypoint`. So passing `-vnc` as command doesn't work.

**Comment by phorcys420** [comment]
yeah but then it's a different issue than the one we thought we had
