### ISSUE TITLE
docker_image.nginx: unable to pull image docker_image.nginx:

### ISSUE THREAD

**Issue by mbellahcene** [kreuzwerker/terraform-provider-docker#419]
terraform {
  required_providers {
    # We recommend pinning to the specific version of the Docker Provider you're using
    # since new versions are released frequently
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.19.0"
    }
  }
}

variable "ssh_host" {}
variable "ssh_user" {}
variable "ssh_key" {}

provider "docker" {
  #host = "tcp://${var.ssh_host}:2375"
  host     = "ssh://${var.ssh_user}@${var.ssh_host}:22"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

resource "docker_image" "ubuntu" {
   name ="ubuntu:latest"
}

resource "docker_container" "foo" {
    depends_on = [
    docker_image.ubuntu
  ]
   image ="docker_image.ubuntu.latest"
   name = "foo"

}

output "host" {
    value = var.ssh_host
}

output "private_key" {
    value = var.ssh_key
}

output "ssh_user" {
    value = var.ssh_user
}

the command line terroform apply -auto-approve

result

Plan: 1 to add, 0 to change, 0 to destroy.
docker_container.foo: Creating...
╷
│ Error: Unable to create container with image docker_image.ubuntu.latest: unable to pull image docker_image.ubuntu.latest: error pulling image docker_image.ubuntu.latest: Error response from daemon: pull access denied for docker_image.ubuntu.latest, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
│
│   with docker_container.foo,
│   on main.tf line 28, in resource "docker_container" "foo":
│   28: resource "docker_container" "foo" {

i cant have a contener ; 
docker images return i good list
but docker ps return 0 contener

**Comment by yuriy-yarosh** [comment]
@mbellahcene

Just remove the quotes, and [read the docs](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#example-usage)

```
resource "docker_container" "foo" {
  depends_on = [
    docker_image.ubuntu
  ]
  image =docker_image.ubuntu.latest
  name = "foo"
}
```

**Comment by mbellahcene** [comment]
# docker_image.ubuntu will be updated in-place
  ~ resource "docker_image" "ubuntu" {
        id          = "sha256:27941809078cc9b2802deb2b0bb6feed6c236cde01e487f200e24653533701eeubuntu:latest"
      ~ name        = "ubuntu:latest" -> "ubuntu:precise"
        # (2 unchanged attributes hidden)
    }

Plan: 1 to add, 1 to change, 0 to destroy.
docker_image.ubuntu: Modifying... [id=sha256:27941809078cc9b2802deb2b0bb6feed6c236cde01e487f200e24653533701eeubuntu:latest]
docker_image.ubuntu: Still modifying... [id=sha256:27941809078cc9b2802deb2b0bb6feed...e01e487f200e24653533701eeubuntu:latest, 10s elapsed]
docker_image.ubuntu: Modifications complete after 16s [id=sha256:5b117edd0b767986092e9f721ba2364951b0a271f53f1f41aff9dd1861c2d4feubuntu:precise]
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for docker_container.foo to include new values learned so far during apply, provider "registry.terraform.io/kreuzwerker/docker" produced an invalid new value for .image: was cty.StringVal("sha256:27941809078cc9b2802deb2b0bb6feed6c236cde01e487f200e24653533701ee"), but now
│ cty.StringVal("sha256:5b117edd0b767986092e9f721ba2364951b0a271f53f1f41aff9dd1861c2d4fe").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

my new code


terraform {
  required_providers {
    # We recommend pinning to the specific version of the Docker Provider you're using
    # since new versions are released frequently
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.19.0"
    }
  }
}

variable "ssh_host" {}
variable "ssh_user" {}
variable "ssh_key" {}


provider "docker" {
  #host = "tcp://${var.ssh_host}:2375"
  host     = "ssh://${var.ssh_user}@${var.ssh_host}:22"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}



resource "docker_container" "foo" {
   name = "foo"
   image =docker_image.ubuntu.latest
   
}

resource "docker_image" "ubuntu" {
   name ="ubuntu:precise"
}


output "host" {
    value = var.ssh_host
}

output "private_key" {
    value = var.ssh_key
}

output "ssh_user" {
    value = var.ssh_user
}

**Comment by mbellahcene** [comment]
i run same code of documentation

**Comment by mbellahcene** [comment]
when i run it with clean project ( init / plan / apply )
i have this message

Plan: 1 to add, 0 to change, 0 to destroy.
docker_container.foo: Creating...
╷
│ Error: container exited immediately
│
│   with docker_container.foo,
│   on main.tf line 25, in resource "docker_container" "foo":
│   25: resource "docker_container" "foo" {

**Comment by mbellahcene** [comment]
terraform {
  required_providers {
    # We recommend pinning to the specific version of the Docker Provider you're using
    # since new versions are released frequently
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.19.0"
    }
  }
}

variable "ssh_host" {}
variable "ssh_user" {}
variable "ssh_key" {}


provider "docker" {
  host     = "ssh://${var.ssh_user}@${var.ssh_host}:22"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

resource "docker_image" "nginx" {
   name ="nginx:latest"
}

resource "docker_container" "foo" {
    depends_on = [
    docker_image.nginx
  ]
   image =docker_image.nginx.latest
   name = "foo"


}


output "host" {
    value = var.ssh_host
}

output "private_key" {
    value = var.ssh_key
}

output "ssh_user" {
    value = var.ssh_user
}


with nginx its ok , with ubuntu not :-(

**Comment by yuriy-yarosh** [comment]
I'm not sure what exactly do you want to do with an empty ubuntu non-interactive container ... 
i.e. there's nothing running there [except bash](https://hub.docker.com/layers/ubuntu/library/ubuntu/latest/images/sha256-cd3d86f1fb368c6a53659d467560010ab9e0695528127ea336fe32f68f7ba09f?context=explore) in non-interactive will exit immediately, which is obvious.

Copy-pasting from the docs and expecting magic to happen without understanding much is not the wisest choice ...
You don't need to run an "ubuntu container" in order to run a "nginx container".

This does not makes any sense
```hcl
resource "docker_container" "foo" {
  name = "foo"
  image =docker_image.ubuntu.latest
}
```

**Comment by Junkern** [comment]
@mbellahcene thanks for submitting this issue! Would be great if you could properly format your posts in the future, it is really hard to look at them and extract the necessary information.

@yuriy-yarosh has already pointed out all the different things you could improve in your code (thanks to you, Yuriy!).

Regarding the "bug" (`When expanding the plan for docker_container.foo to include new values learned so far during apply, provider "registry.terraform.io/kreuzwerker/docker" produced an invalid new value for .image: was cty.StringVal("sha256:27941809078cc9b2802deb2b0bb6feed6c236cde01e487f200e24653533701ee"), but now
│ cty.StringVal("sha256:5b117edd0b767986092e9f721ba2364951b0a271f53f1f41aff9dd1861c2d4fe").`), this I will hopefully tackle in the near future.
