### ISSUE TITLE
Support for tagging image

### ISSUE THREAD

**Issue by normander** [kreuzwerker/terraform-provider-docker#420]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have some tasks to do, the best idea will be to do it in the Terraform, and I'm wondering if maybe someone else will use this feature also.
In case of having all necessary Docker images inside of a special cloud - like AWS or Azure I need to retag some official images from Dockerhub to a private registry in the cloud, some images like Ingress Nginx will be needed in the Terraform operations and we could used this method to synchronize all images in some pipeline afterward using the same provider.

What do you think about this? Do someone has some experience with this? Will it be useful for someone else?

* #0000

**Comment by Junkern** [comment]
With `v2.20.0` we just released a `docker_tag` resource which does the same thing as the  `docker tag` command.

In your use case I would suggest you to use a software which keeps docker registries in sync (copying images over from dockerhub to ECR). I have used https://github.com/xelalexv/dregsy in various projects, it always worked like a charm.
