### ISSUE TITLE
docker_image: attribute "latest" is deprecated, but tutorial uses it

### ISSUE THREAD

**Issue by claviola** [kreuzwerker/terraform-provider-docker#452]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

```
Terraform v1.2.8
on darwin_amd64
+ provider registry.terraform.io/kreuzwerker/docker v2.20.3
```

### Affected Resource(s)

* `docker_image`

### Terraform Configuration Files

```hcl
# Set the required provider and versions
terraform {
  required_providers {
    # We recommend pinning to the specific version of the Docker Provider you're using
    # since new versions are released frequently
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.20.3"
    }
  }
}

# Configure the docker provider
provider "docker" {
}

# Create a docker image resource
# -> docker pull nginx:latest
resource "docker_image" "nginx" {
  name         = "nginx:latest"
  keep_locally = true
}

# Create a docker container resource
# -> same as 'docker run --name nginx -p8080:80 -d nginx:latest'
resource "docker_container" "nginx" {
  name    = "nginx"
  image   = docker_image.nginx.latest

  ports {
    external = 8080
    internal = 80
  }
}
```

### Debug Output

https://gist.github.com/claviola/4593a5490d53bda110318f6ea7c3a6ef

### Expected Behaviour

No warnings for the tutorial

### Actual Behaviour

Tutorial causes warnings

### Steps to Reproduce

1. Save contents of [example usage](https://github.com/kreuzwerker/terraform-provider-docker#example-usage) tutorial to file in empty directory
2. `terraform init`
3. `terraform plan`

### References

* #347 - seems to relate to this issue, but it's not clear to me if `repo_digest` is a drop-in replacement for `latest`.

**Comment by LeoShivas** [comment]
Solution :
As the [release 2.21.0](https://github.com/kreuzwerker/terraform-provider-docker/releases/tag/v2.21.0) ships the [#453 fix](https://github.com/kreuzwerker/terraform-provider-docker/pull/453) :
on `versions.tf` line 5, in terraform {  required_providers { docker } } }:
Replace version = \"\~> 2.**16**.0"
By version = \"\~> 2.**21**.0"

on `nginx/versions.tf` line 5, in terraform {  required_providers { docker } } }:
Replace version = \"\~> 2.**16**.0"
By version = \"\~> 2.**21**.0"

Also :
on `main.tf` line 10, in resource "docker_container" "nginx":
Replace image = docker_image.nginx.**latest**
By image = docker_image.nginx.**image_id**

on `nginx/main.tf` line 10, in resource "docker_container" "nginx":
Replace image = docker_image.nginx.**latest**
By image = docker_image.nginx.**image_id**

**_Extra :_**
on `main.tf` line 34, in module "hello":
Replace secret_key = **var.secret_key**
By secret_key = **"secret"**

And do :
```
terraform init -upgrade
terraform plan -out tfplan
```
