### ISSUE TITLE
build options for docker_image and docker_registry_image should be consistent

### ISSUE THREAD

**Issue by robomon1** [kreuzwerker/terraform-provider-docker#458]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/kreuzwerker/docker v2.21.0

### Affected Resource(s)

- docker_image
- docker_registry_Image

### Terraform Configuration Files

```hcl
resource "docker_image" "example_image" {
  name = "example_image"
  build {
    path = "."
    build_arg = {
      test ="true"
    }
  }
}

resource "docker_registry_image" "example_registry_image" {
  name = "example_registry_image"
  build {
    context = "."
    build_args = {
      test ="true"
    }
  }
}

```

### Expected Behaviour

I expect that docker_image and docker_registry_image resources use the same schema where possible. For example:

- path vs context - They both do the same thing
- build_arg vs build_args - Plural vs Singular and they do the same thing
- tag vs ? - No tag in build options for docker_registry_image.  It goes in the name field?

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Junkern** [comment]
Thanks for the issue! You are totally right. It it actually the next thing on my list to move all the `build` options over to the `docker_image` resource, so that we have one single resource for building docker images. The `docker_registry_image` will still be there, but will be solely responsible for managing a docker registry image. There will be deprecation notices.
