### ISSUE TITLE
[docker_network] - check_duplicate not working

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#47]
<i>This issue was originally opened by @pumpingiron as https://github.com/hashicorp/terraform-provider-docker/issues/299. It was migrated here as a result of the community provider takeover from @kreuzwerker. The original body of the issue is below.</i><hr>
Hello everyone,

The boolean option referenced in the title doesn't work, even when set to true, I get two networks with the same name but different ids.

![image](https://user-images.githubusercontent.com/3579763/95886080-66ff9b80-0d7e-11eb-9b40-299ad8a861b6.png)
![image](https://user-images.githubusercontent.com/3579763/95886129-7848a800-0d7e-11eb-9afb-3cc0de33456d.png)

Have you got a clue ?

**Comment by andrewv22** [comment]
@pumpingiron can you provide some steps to reproduce? or even a concrete example where this happens? I can't seem to reproduce this issue in any way.
