### ISSUE TITLE
Upgrade to Docker Desktop v4.15.0 macOS throws an error on docker images with forward slashes in them

### ISSUE THREAD

**Issue by nacengineer** [kreuzwerker/terraform-provider-docker#484]
### Terraform Info 

On latest version from homebrew 

```
❯ terraform version
Terraform v1.3.6
on darwin_amd64
+ provider registry.terraform.io/kreuzwerker/docker v2.23.1
```
Could be a docker issue but I am able to pull and run the images through docker desktop so guessing it's something specific to terraform or terraform docker module. Perhaps an escaping issue of forward slashes. 

### Docker info
On macos Intel mac.
 
Works on Docker Desktop version 4.14.1 (91661) breaks on update to 4.15.0 (93002). Tested identical script on both. 

It seems to break on docker hub images with forward slashes in them, e.g. livebook/livebook 

### Terraform Info 

A sample tf script to reproduce with ancillary files and output is in this gist. 

https://gist.github.com/nacengineer/1cbb4944b4f00f3d335cf9a6887580d1

### Expected Behaviour

Downloads image and applies plan. 

### Actual Behaviour

Can't find any docker images with forward slashes

### Steps to Reproduce

Setup a tf docker script with an image that uses a forward slash. 

1. `terraform apply -var-file="development.tfvars.json"`

### Important Factoids

Seems to be an issue with only tags with forward slashes in them. 
It happened for this one and another one I run in a larger terraform script to bootstrap my laptop. 
Rolling back to 4.14.1 docker desktop on macos makes it work again.

**Comment by Junkern** [comment]
I tested your code, it worked perfectly fine for me (apart from the `volumes` config).
Are you sure that this is not an issue with your internet connection or a hickup on dockerhubs end?
Because in the error log we can see that `error reading from server: EOF` (3rd last line)

**Comment by nacengineer** [comment]
Well I'm on university networking so probably not as it's 100MB async. I would say it's firewall but rolling back to 4.14 completely fixes the issue. Also I've now upgraded to Ventura and on Ventura 13.1 + 4.15 all of the pulls fail. I'll try it later on my personal M2 Air and see if the same issue persists. Who knows. Maybe it's an intel mac issue. I'll post again later from my Air.

**Comment by nacengineer** [comment]
OK I took another stab at fixing this one. Looks like the update turned on this beta feature

"Use containerd for pulling and storing images" 

and that is what seems to be breaking it. When I uncheck it then it works albeit the slows are reeeallly slow. Closing this as it's an beta feature but figured you'd want to know about it.
