### ISSUE TITLE
Container grouping for Docker Desktop

### ISSUE THREAD

**Issue by MichaelVeit-GFT** [kreuzwerker/terraform-provider-docker#516]
It would be nice to provide grouping of containers.
In Docker Desktop, when using docker-compose.yml, the "Name:" property allows to group all containers under this name.

When having several projects in Docker Desktop, it's much easier if I don't need to think of unique container names across different projects. Even when having quite simple container names in projects, like "mongo" or "maria-db" etc., the project grouping is quite useful, instead of having "project1-mongo", "project2-mongo".

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* docker_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by Junkern** [comment]
I think that's a feature of `docker-compose`, you can provide a project name and it prepends all containers names with that project name (https://docs.docker.com/compose/environment-variables/envvars/#compose_project_name)

As we do not support `docker-compose` this is something we can't implement

**Comment by MichaelVeit-GFT** [comment]
Ok, I wasn't aware that docker compose is not integral part of docker.
This page clarifies the architecture of Docker (client), but put on top of Docker for bundle "Docker Desktop":
[Docker - Getting started - Docker architecture](https://docs.docker.com/get-started/overview/)
