### ISSUE TITLE
Questions Issue Template outdated or broken?

### ISSUE THREAD

**Issue by f0o** [kreuzwerker/terraform-provider-docker#518]
Hi!

The issue template for:
```
Terraform Docker Provider Questions
GitHub issues in this repository are only intended for bug reports and feature requests. Other issues will be closed. Please ask and answer questions through the Terraform Docker Provider Slack channel.
```

links to https://gophers.slack.com/archives/C01G9TN5V36 but this slack is not public so how is one supposed to access it and post questions?

**Comment by Junkern** [comment]
Good question. Pinging @mavogel maybe he will know?

**Comment by mavogel** [comment]
Hi @f0o , sorry therefore. Please use the Questions here in GH: https://github.com/kreuzwerker/terraform-provider-docker/discussions

Will update the docs
