### ISSUE TITLE
Unable to find or pull image with digest

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#52]
<i>This issue was originally opened by @viceice as https://github.com/hashicorp/terraform-provider-docker/issues/282. It was migrated here as a result of the community provider takeover from @kreuzwerker. The original body of the issue is below.</i><hr>
### Terraform Version
```
Terraform v0.12.29
+ provider.docker v2.7.1
+ provider.helm v1.2.4
+ provider.kubernetes v1.11.4
```

### Affected Resource(s)
Please list the resources as a list, for example:
- docker_image
- docker_container

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    docker = "2.7.1"
  }
}

provider "docker" {
  host = "ssh://root@docker-worker2"
}

resource "docker_image" "nginx" {
  name     = "nginx:1.18.0-alpine@sha256:29dc24ed982665eb88598e0129e4ec88c2049fafc63125a4a640dd67529dc6d4"
}

resource "docker_container" "nginx" {
  name     = "nginx-example"
  image    = "nginx:1.18.0-alpine@sha256:29dc24ed982665eb88598e0129e4ec88c2049fafc63125a4a640dd67529dc6d4"
  restart  = "unless-stopped"
  start    = true
}
```

### Debug Output
https://gist.github.com/viceice/b1a3b6a462988cf53c49a247b4d090da

### Expected Behavior
pull docker image and create container

### Actual Behavior
fails with error
* `Unable to read Docker image into resource: Unable to find or pull image nginx:1.18.0-alpine@sha256:29dc24ed982665eb88598e0129e4ec88c2049fafc63125a4a640dd67529dc6d4`
* `Unable to create container with image nginx:1.18.0-alpine@sha256:29dc24ed982665eb88598e0129e4ec88c2049fafc63125a4a640dd67529dc6d4: Unable to find or pull image nginx:1.18.0-alpine@sha256:29dc24ed982665eb88598e0129e4ec88c2049fafc63125a4a640dd67529dc6d4`

### Steps to Reproduce
1. `terraform apply -auto-approve  -parallelism=1`

### Important Factoids
Simple docker install on ubuntu 18.04 with btrfs

```
Server:
 Containers: 13
  Running: 0
  Paused: 0
  Stopped: 13
 Images: 82
 Server Version: 19.03.12
 Storage Driver: btrfs
  Build Version: Btrfs v4.15.1
  Library Version: 102
 Logging Driver: journald
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-1032-azure
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.793GiB
 Name: XXXX
 ID: XXXXX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by fabianschurz** [comment]
Same here, i guess that is because the provider uses the image id instead of the digest. Actually i'm pulingl the images to see the image id via `docker image inspect TAG | grep Id` since i did not manage to found a more elegant solution/workaround.

I wish the provider to allow the use of the digest which is the "new" way since docker registry v2.

**Comment by viceice** [comment]
@fabianschurz Workarounf / Solution:

resource "docker_image" "nginx" {
  name = "nginx:1.18.0-alpine@sha256:29dc24ed982665eb88598e0129e4ec88c2049fafc63125a4a640dd67529dc6d4"
}

```hcl
resource "docker_container" "nginx" {
  name     = "nginx-example"
  image    = docker_image.nginx
  restart    = "unless-stopped"
  start       = true
}
```

**Comment by suzuki-shunsuke** [comment]
I could reproduce the problem.

According to the document, `docker_image.name` supports an image digest, but actually doesn't work well.

https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/image#name

> name - (Required, string) The name of the Docker image, including any tags or SHA256 repo digests.

```console
$ terraform version
Terraform v0.14.9
+ provider registry.terraform.io/kreuzwerker/docker v2.11.0
```

```tf
resource "docker_image" "nginx" {
  name = "nginx:1.18.0@sha256:0c56c40f232f41c1b8341c3cc055c8b528cb6decefd7f7c8506e2d30bb9678b6"
}

terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.11.0"
    }
  }
}

provider "docker" {
}
```

We can pull the Docker image by `docker pull` command, but `terraform apply` failed.

```console
$ terraform apply                                                                                          

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # docker_image.nginx will be created
  + resource "docker_image" "nginx" {
      + id     = (known after apply)
      + latest = (known after apply)
      + name   = "nginx:1.18.0@sha256:0c56c40f232f41c1b8341c3cc055c8b528cb6decefd7f7c8506e2d30bb9678b6"
      + output = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

docker_image.nginx: Creating...

Error: Unable to read Docker image into resource: Unable to find or pull image nginx:1.18.0@sha256:0c56c40f232f41c1b8341c3cc055c8b528cb6decefd7f7c8506e2d30bb9678b6

  on main.tf line 1, in resource "docker_image" "nginx":
   1: resource "docker_image" "nginx" {

$ docker pull "nginx:1.18.0@sha256:0c56c40f232f41c1b8341c3cc055c8b528cb6decefd7f7c8506e2d30bb9678b6"
docker.io/library/nginx@sha256:0c56c40f232f41c1b8341c3cc055c8b528cb6decefd7f7c8506e2d30bb9678b6: Pulling from library/nginx
e95f33c60a64: Pull complete 
8b052b3c1a10: Pull complete 
a4f5d275d76e: Pull complete 
926c236b9574: Pull complete 
f049360d30a6: Pull complete 
Digest: sha256:0c56c40f232f41c1b8341c3cc055c8b528cb6decefd7f7c8506e2d30bb9678b6
Status: Downloaded newer image for nginx@sha256:0c56c40f232f41c1b8341c3cc055c8b528cb6decefd7f7c8506e2d30bb9678b6
docker.io/library/nginx:1.18.0@sha256:0c56c40f232f41c1b8341c3cc055c8b528cb6decefd7f7c8506e2d30bb9678b6
```

**Comment by suzuki-shunsuke** [comment]
I found that a Docker image tag `1.18.0` isn't included in `RepoDigests`.

```console
$ docker inspect "nginx:1.18.0@sha256:0c56c40f232f41c1b8341c3cc055c8b528cb6decefd7f7c8506e2d30bb9678b6" | ag -A 3 RepoDigests
        "RepoDigests": [
            "nginx@sha256:0c56c40f232f41c1b8341c3cc055c8b528cb6decefd7f7c8506e2d30bb9678b6"
        ],
        "Parent": "",
```

**Comment by suzuki-shunsuke** [comment]
If we remove the image tag, then it works well.

```tf
resource "docker_image" "nginx" {
  # remove `:1.18.0`
  # name = "nginx:1.18.0@sha256:0c56c40f232f41c1b8341c3cc055c8b528cb6decefd7f7c8506e2d30bb9678b6"
  name = "nginx@sha256:0c56c40f232f41c1b8341c3cc055c8b528cb6decefd7f7c8506e2d30bb9678b6"
}

terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.11.0"
    }
  }
}

provider "docker" {
}
```

```console
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # docker_image.nginx will be created
  + resource "docker_image" "nginx" {
      + id     = (known after apply)
      + latest = (known after apply)
      + name   = "nginx@sha256:0c56c40f232f41c1b8341c3cc055c8b528cb6decefd7f7c8506e2d30bb9678b6"
      + output = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

docker_image.nginx: Creating...
docker_image.nginx: Creation complete after 5s [id=sha256:2dd397812ae1957ba18df0a62f0bcfa4ea3150027deab92cef0adf80803d0853nginx@sha256:0c56c40f232f41c1b8341c3cc055c8b528cb6decefd7f7c8506e2d30bb9678b6]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by fabianschurz** [comment]
But still the provider uses the image id not the digest from docker hub, or am i wrong?
When i use the digest from docker hub i get an error that the image could not be found. If i use the image id then it works as expected but i have to pull the image before and inspect it to get the image id because it's not being shown in docker hub.

I did not define a docker image resource instead i directly wrote the SHA into double quotes after the equals sign of image.

```
resource "docker_container" "portainer" {
  image = "sha256:96a1c6cc3d158fac0b5be75382b9b24d0a89ed5db7a59a3442d01556c139fff1" # portainer/portainer-ce:2.1.1
```

If i insert the digest there i get an error as already said. But i did not try to define the image via image resource.

@suzuki-shunsuke 
Does your configuration work with the digest?

**Comment by suzuki-shunsuke** [comment]
`docker_container.image` is not an image digest but an image id.
It's documented.

https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#image

> image - (Required, string) The ID of the image to back this container. The easiest way to get this value is to use the docker_image resource as is shown in the example above.

**Comment by suzuki-shunsuke** [comment]
I have created a pull request to fix https://github.com/kreuzwerker/terraform-provider-docker/issues/52#issuecomment-806581094 .

https://github.com/kreuzwerker/terraform-provider-docker/pull/151

**Comment by fabianschurz** [comment]
Yeah but to get the image id i need to pull the actual image. The digest is what's being shown in the docker hub so it should be possible to use it

**Comment by tafaust** [comment]
Sorry for the necrobump but this error reappears for me in 3.0.2.

Image I'm trying to pull:
```
data "docker_image" "database_image" {
  name = "postgres:16.1-alpine"
}
```

uname -a (of the machine that I want to terraform
`Linux redacted 5.15.0-89-generic #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

I also have another ghcr.io private registry for which it does not work as well:

```
provider "docker" {
  host     = "ssh://user@bastion:2222"
  ssh_opts = ["-F", pathexpand(var.SSH_CONFIG), "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]

  registry_auth {
    address  = "ghcr.io"
    username = var.GHCR_REGISTRY_AUTH.username              # use github.actor
    password = var.GHCR_REGISTRY_AUTH.personal_access_token # use secrets.GITHUB_TOKEN
  }
}
```

Any ideas? What other information shall I need to provide?
