### ISSUE TITLE
Cannot use docker_registry_image behind a proxy

### ISSUE THREAD

**Issue by baptman21** [kreuzwerker/terraform-provider-docker#528]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When using the provider behing a proxy, the getImageDigest function fails to
retrieve the digest from the registry. This causes any use of
`docker_registry_image` (resource or data) to fail during the apply.

### Terraform (and docker Provider) Version

```
$ terraform -v
Terraform v1.4.1
on windows_386
+ provider registry.terraform.io/kreuzwerker/docker v3.0.1
```

### Affected Resource(s)

* resource `docker_registry_image`
* data `docker_registry_image`

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.15"

  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = ">= 3.0.1"
    }
  }
}

provider "docker" {
  registry_auth {
    address       = "registry.domain.com"
    auth_disabled = true
  }
}

data "docker_registry_image" "test_image" {
  name = "registry.domain.com/test_image:latest"
}

output "digest" {
  value = data.docker_registry_image.test_image.sha256_digest
}
```

### Debug Output

```
Error: Got error when attempting to fetch image version registry.domain.com/test_image:latest from registry: Error during registry request: Head "https://registry.domain.com/v2/test_image/manifests/latest": EOF
```

### Expected Behaviour

The digest should have been retrieved from the registry without any problem.

The image exists on the registry and the HEAD request works with CURL and
the python requests libraries. I am here using a locally deployed registry for
debugging but docker hub or GCP Artifact registry also fails.

### Actual Behaviour

The requests to get the digest fails and the terraform apply fails.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I am using terraform behind a proxy, requests to the registry directly are
therefore blocked (`curl -I https://registry.domain.com/v2/` would break if you
don't set HTTPS_PROXY variable).

Without a proxy the requests works and the terraform apply works with this configuration.

### Source of the Bug

After some minor investigation I think the problem comes from the
[`getImageDigest`](https://github.com/kreuzwerker/terraform-provider-docker/blob/master/internal/provider/data_source_docker_registry_image.go#L76)
function. It calls the [`buildHttpClientForRegistry`](https://github.com/kreuzwerker/terraform-provider-docker/blob/master/internal/provider/resource_docker_registry_image_funcs.go#L249)
function that creates a default http client.

But when creating this client it overrides the `client.Transport`. The new
`Transport` object created does not have `Proxy` attribute set to
`ProxyFromEnvironment`.

This means that for the calls for the digest, no proxy configuration is passed
to the client, i.e. the provider cannot be used behind a proxy.

**Comment by Junkern** [comment]
Fix released in `v3.0.2`
