### ISSUE TITLE
triggers for resource docker image not expected 

### ISSUE THREAD

**Issue by aesansun** [kreuzwerker/terraform-provider-docker#538]
resource "docker_image" "imagegreat" {
    
   name = "greatimage"
     build {
          path = "../docker"
          dockerfile = "Dockerfile"
          tag     =  ["${aws_ecr_repository.ecs_repo.repository_url}:v1.0"]
  }
   triggers = {
    dir_sha1 = sha1(join("", [for f in fileset(path.module, "docker/*") : filesha1(f)]))
  }

}

Trying to trigger a docker rebuild image every time the file changes.  When i run a terraform plan " An argument named "triggers" is not expected here." seems the documentation might be wrong

**Comment by Junkern** [comment]
This was implement with https://github.com/kreuzwerker/terraform-provider-docker/commit/59fcfcc269d51dadeda3c5d0f4f19f20036c1f46 and released with `2.20.1`.
Are you using an older version? You can check the used providers by running `terraform providers`.

**Comment by aesansun** [comment]
that fixed the issue, thank you.
