### ISSUE TITLE
Docker pull command pulls from cache - not getting latest image 

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#58]
<i>This issue was originally opened by @wereinse as https://github.com/hashicorp/terraform-provider-docker/issues/267. It was migrated here as a result of the community provider takeover from @kreuzwerker. The original body of the issue is below.</i><hr>
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.21

### Affected Resource(s)
Please list the resources as a list, for example:
Docker image version 

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
See changes below:

![image](https://user-images.githubusercontent.com/51492074/81724661-bdc11c00-9452-11ea-92c6-f2bfb00a8724.png)

Changes made are below:
This is from :  https://github.com/retaildevcrews/helium-iac/blob/master/src/modules/db/main.tf 

```tf
resource "azurerm_cosmosdb_sql_container" "cosmosdb-movies" {
  for_each            = var.INSTANCES
  name                = "movies"
  resource_group_name = var.COSMOS_RG_NAME
  account_name        = azurerm_cosmosdb_account.cosmosdb.name
  database_name       = azurerm_cosmosdb_sql_database.cosmosdb-imdb[each.key].name
  partition_key_path  = "/partitionKey"
}

data "docker_registry_image" "imdb-import" {
  name = "retaildevcrew/imdb-import"
}

resource "docker_image" "imdb-import" {
  name          = data.docker_registry_image.imdb-import.name
  pull_triggers = ["${data.docker_registry_image.imdb-import.sha256_digest}"]
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
resource "docker_image" "imdb-import"  should have pulled the latest image

### Actual Behavior
What actually happened?
The above command pulled a cached image instead of going back for the original.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` with the resource "docker_image" "imdb-import" command in place .
2. Run once
3. Change the image
4. Run again and you should get the older image

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by wereinse** [comment]
The resource is pulling a cached image and not going back for the latest. Why isn’t that an issue?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mavogel** [comment]
Hey @wereinse it is an issue and we will solve it. Or did I get you wrong?

**Comment by wereinse** [comment]
To me it's an issue if a cached image is pulled.  specifying :latest does resolve the issue but then the docs would be more helpful if they reflected that.

**Comment by mavogel** [comment]
Ok thanks for the update
