### ISSUE TITLE
Connect via SSH with key

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#61]
<i>This issue was originally opened by @alexborisov as https://github.com/hashicorp/terraform-provider-docker/issues/259. It was migrated here as a result of the community provider takeover from @kreuzwerker. The original body of the issue is below.</i><hr>
How can I use key authentication when connecting via ssh?

**Comment by mavogel** [comment]
@alexborisov can you be more specific how you want to use the provider? An example would help us :)

**Comment by suzuki-shunsuke** [comment]
Duplicated with #29
