### ISSUE TITLE
Upload file with new timestamp

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#67]
<i>This issue was originally opened by @mleonhard as https://github.com/hashicorp/terraform-provider-docker/issues/246. It was migrated here as a result of the community provider takeover from @kreuzwerker. The original body of the issue is below.</i><hr>
### Terraform Version
```
Terraform v0.12.20
+ provider.digitalocean v1.14.0
+ provider.docker v2.7.0   <--- Latest version as of 2012-03-12
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.tls v2.1.1
+ provider.twilio (unversioned)
```

### Affected Resource(s)
- docker_container

### Terraform Configuration Files
```hcl
resource "docker_container" "grafana" {
  name = "grafana"
  user = "1000"
  upload {
    file = "/etc/grafana/provisioning/dashboards/containers.json"
    content = file("${path.module}/containers.json")
  }
  ...
}
```

### Expected Behavior
I need Terraform to update the timestamp of the uploaded file when it changes the file's contents.

### Actual Behavior
Terraform currently uploads the file and sets its timestamp to 0.  It also sets its owner to `root`.  A non-root container cannot update the file timestamp.

```
root@staging19:~# docker exec -t -i grafana sh
/usr/share/grafana $ ls -alF /etc/grafana/provisioning/dashboards/containers.json
-rw-r--r--    1 root     root         32101 Jan  1  1970 /etc/grafana/provisioning/dashboards/containers.json
/usr/share/grafana $ touch /etc/grafana/provisioning/dashboards/containers.json
touch: /etc/grafana/provisioning/dashboards/containers.json: Permission denied
/usr/share/grafana $ 
```

**Comment by aequitas** [comment]
I'm running into the same issue with Grafana.

The reason why the file gets a epoch timestamp is due to this part: https://github.com/kreuzwerker/terraform-provider-docker/blob/ca2663562579a7094e1990c7cbeb48cb59ab1c85/internal/provider/resource_docker_container_funcs.go#L436

The upload file is tar'd, but no `ModTime` parameter is given in the header so it defaults to the `time.Time` zero value which is 1 Jan 1970.

The solution might be as simple as to add the `ModTime` value to the header. Only question is what value to use. Maybe just the current timestamp for `content` and the source file's timestamp for `source`, or should we default to just the current time for both?

**Comment by mavogel** [comment]
@aequitas I used the current timestamp for both.
The next question is: shall we use the `user` who is running the container the be the one owning the file?

**Comment by mavogel** [comment]
Retesting with the docker cli, the file also gets copied with `root` as the owner per default
```Dockerfile
FROM grafana/grafana

USER 1000
COPY containers.json /etc/grafana/provisioning/dashboards/containers.json
```
with the following commands:
```sh
docker build -t issue-67 .
docker run -d --name grafana issue-67

docker exec grafana ls -alF /etc/grafana/provisioning/dashboards/
total 16
drwxrwxrwx    1 grafana  root          4096 Aug 10 08:27 ./
drwxrwxrwx    1 grafana  root          4096 Aug  9 13:47 ../
-rw-r--r--    1 root     root             9 Aug 10 08:23 containers.json
```

You could also user the `COPY --chown=user:group <src> <dst>` flag. As a solution, we could set this for the upload block with the  [CopyUIDGID](https://github.com/moby/moby/blob/c485e901d9d305dab8d262735714734353a6b1ba/api/types/client.go#L100) option
