### ISSUE TITLE
docker_container: Add support for id in networks_advanced block

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#79]
<i>This issue was originally opened by @captn3m0 as https://github.com/hashicorp/terraform-provider-docker/issues/184. It was migrated here as a result of the community provider takeover from @kreuzwerker. The original body of the issue is below.</i><hr>
### Terraform Version
`v0.11.13`

### Affected Resource(s)
Please list the resources as a list, for example:
- `docker_container`

### Terraform Configuration Files
```hcl
resource "docker_container" "c" {
// name, image etc
networks_advanced = [
  {
    name = "${docker_network.n.id}"
  }
]
}

resource "docker_network" "n" {
  name = "network-name"
}
```

Right now, `docker_network` resource only exports the `id`, which is not consumed by the `docker_container` resource. This issue means I can't connect a network with a container as a dependency graph.

**Comment by Junkern** [comment]
I just tried to reproduce this.
Using both `docker_network.n.name` and `docker_network.n.id` as a value for the `name` attribute works and creates running docker_containers.
Also the dependency graph is built correctly.

**Comment by captn3m0** [comment]
Perhaps the docs for `networks_advanced` should be updated to reflect the same? (network ID being accepted in the `name` parameter)

https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#nested-schema-for-networks_advanced

**Comment by Junkern** [comment]
Good suggestion, thank you!

**Comment by Junkern** [comment]
Small improvement implemented in https://github.com/kreuzwerker/terraform-provider-docker/commit/074c94cabc2ea3d1132c27f89f1ae05758f04146
Will have to wait for the next release to be viewable in the official terraform docs
