### ISSUE TITLE
Container is not stopped when using `rm=true`

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#81]
<i>This issue was originally opened by @inercia as https://github.com/hashicorp/terraform-provider-docker/issues/163. It was migrated here as a result of the community provider takeover from @kreuzwerker. The original body of the issue is below.</i><hr>
### Terraform Version
Terraform v0.11.15-dev
+ provider.docker v2.0.0

### Affected Resource(s)
- docker_container

### Terraform Configuration Files
```hcl
provider "docker" {
  host = "tcp://127.0.0.1:2375/"
}

resource "docker_network" "network" {
  name            = "haproxy-test-net"
  check_duplicate = "true"
}

resource "docker_container" "haproxy-test" {
  name                  = "haproxy-test"
  image                 = "haproxy"
  start                 = true
  rm                    = true
  privileged            = true
  must_run              = true
  restart               = "no"
  destroy_grace_seconds = 60
  network_mode          = "bridge"

  upload {
    file    = "/usr/local/etc/haproxy/haproxy.cfg"
    content = <<EOF
    defaults
      timeout connect 10s
      timeout client 86400s
      timeout server 86400s

    frontend apiserver
      bind :6443
      default_backend apiserver-backend

    backend apiserver-backend
      option httpchk GET /healthz
      server localhost 127.0.0.1:6443 check check-ssl verify none
EOF

  }
}
```

### Debug Output
[cluster creation](https://gist.github.com/inercia/f1d83d434319d841a3a629c5e5b355cc)
[cluster destruction](https://gist.github.com/inercia/ce43d299af21623489655822e3818a1a)

### Expected Behavior
The docker container should have been properly stopped, but it is still running after `terraform destroy`. A `docker ps` shows the container running.

### Actual Behavior

From [the docs](https://www.terraform.io/docs/providers/docker/r/container.html#rm) _"If true, then the container will be automatically removed after his execution. Terraform won't check this container after creation."_, so it seems to be equivalent to the `--rm` flag of `docker`. However, the docker container is not stopped at all (let alone to be removed). Maybe the `rm` argument is not preoperly explained in the docs.

Looking at the code, it seems the only thing the provider does when destroying the container with `rm=true` [is to remove the ID](https://github.com/terraform-providers/terraform-provider-docker/blob/master/docker/resource_docker_container_funcs.go#L560-L563).

### Steps to Reproduce
1. Use `rm=true` in a container.
2. `terraform apply`
3. `terraform destroy`

**Comment by birnbera** [comment]
I can second that this is still an issue. It seems that `destroy` doesn't stop running containers regardless of the value for `rm`.
