### ISSUE TITLE
Docker service support for host networking

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#83]
<i>This issue was originally opened by @hashibot[bot] as https://github.com/hashicorp/terraform-provider-docker/issues/160. It was migrated here as a result of the community provider takeover from @kreuzwerker. The original body of the issue is below.</i><hr>
_This issue was originally opened by @cjbdev as hashicorp/terraform#21729. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Current Terraform Version

```
Terraform v0.11.14
```

### Use-cases

There is a docker container I'm trying to deploy in a swarm with Terraform that requires host networking. The ports of the container change randomly with each deployment, so manually defining each port is not an option

### Proposal

As of Docker 17.06 and higher, Docker supports host networking for services by specifying `--network host` when creating the service [(https://docs.docker.com/network/host/](https://docs.docker.com/network/host/)). Here is my idea of what this could look like in Terraform:

```
resource "docker_service" "foo" {
  name = "foo-service"
  network = "host"

  ...

}
```

**Comment by tomalok** [comment]
To my knowledge this hasn't yet been addressed.

**Comment by tomalok** [comment]
Using this...
```
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.12.2"
    }
  }
}

provider "docker" {
}

resource "docker_service" "foo" {
  name = "foo-service"

  task_spec {
    container_spec {
      image = "nginx"
    }
    networks = [
      "host"
    ]
  }
}
```
...which ***does*** actually `apply`!

Doing a ``docker inspect`` on the resulting container, shows...
```
        "NetworkSettings": {
[...]
            "Networks": {
                "host": {
                    "IPAMConfig": {},
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "e04bb7517e0e6c8c90fc80f45b79a21008da142371f642ffd0dd982db1f24fe0",
                    "EndpointID": "e87873fe3d1058ab02c86096381252a3aef4f44309e31bbce995cfb82782bfbe",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
```
...and the `NetworkID` matches the right network on the swarm node...
```
jake@jimini host-network % docker network ls
NETWORK ID     NAME              DRIVER    SCOPE
ae56e058c659   bridge            bridge    local
ca314bd6996c   docker_gwbridge   bridge    local
e04bb7517e0e   host              host      local
4l41rrjodroh   ingress           overlay   swarm
0c838fe2878a   none              null      local
```

Will need to do some more testing (on a swarm larger than one node, and mix in an overlay network or two), but this is encouraging.

**Comment by mavogel** [comment]
good to hear @tomalok :) I think this has been addressed in #202. Will close the issue for now. I the issue still persists please re-open it. Thank you

**Comment by tomalok** [comment]
I think that #202 is a separate issue (populating /etc/hosts inside the container for DNS purposes), whereas this is more about being able to associate a service with _the_ "host" network/driver.

Being able to specify service networks **by name** means that the service should be able to use the host network on the nodes that it runs on -- every node in the swarm has its own separate host network.

The [current documentation](https://github.com/kreuzwerker/terraform-provider-docker/blob/master/docs/resources/service.md) implies that service networks are instead **by ID** which is perhaps no longer the only way to do so.

**Comment by mavogel** [comment]
Ok, if I get it right, you'd also like to pass the network by name and not only by id, right?
