### ISSUE TITLE
Empty ports state when network_mode is set to "host"

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#84]
<i>This issue was originally opened by @dylanPowers as https://github.com/hashicorp/terraform-provider-docker/issues/148. It was migrated here as a result of the community provider takeover from @kreuzwerker. The original body of the issue is below.</i><hr>
### Terraform Version
Terraform v0.11.14
+ provider.docker v1.1.1
+ provider.external v1.1.2

### Affected Resource(s)
- docker_container

### Terraform Configuration Files
```hcl
resource "docker_container" "fail" {
  name = "fail"
  image = "ubuntu:latest"
  network_mode = "host"
  command = "sleep inf"

  ports {
    internal = 8080
    external = 8080
    ip = "127.0.0.1/32"
  }
}
```

### Expected Behavior
There should be no changes detected immediately after creating the resource.

### Actual Behavior
Changes are detected because the port state is lost. This appears to be limited to only the reading back of the docker configuration because the container is deployed with the correct configuration.
```
-/+ docker_container.fail (new resource required)
      id:               "e55290e4b11775d1ea004e5fd06e6e94d80bd17513ae077ea088935e81dc940d" => <computed> (forces new resource)
      attach:           "" => "false"
      bridge:           "" => <computed>
      command.#:        "2" => "2"
      command.0:        "sleep" => "sleep"
      command.1:        "inf" => "inf"
      container_logs:   "" => <computed>
      exit_code:        "" => <computed>
      gateway:          "" => <computed>
      image:            "ubuntu:latest" => "ubuntu:latest"
      ip_address:       "" => <computed>
      ip_prefix_length: "0" => <computed>
      log_driver:       "json-file" => "json-file"
      logs:             "" => "false"
      must_run:         "true" => "true"
      name:             "fail" => "fail"
      network_data.#:   "1" => <computed>
      network_mode:     "host" => "host"
      ports.#:          "0" => "1" (forces new resource)
      ports.0.external: "" => "8080" (forces new resource)
      ports.0.internal: "" => "8080" (forces new resource)
      ports.0.ip:       "" => "127.0.0.1/32" (forces new resource)
      ports.0.protocol: "" => "tcp" (forces new resource)
      restart:          "no" => "no"
      rm:               "" => "false"
      start:            "" => "true"
```

### Steps to Reproduce
1. `terraform apply`
2. `terraform apply`

**Comment by Junkern** [comment]
Whe using `host` network mode, the port mapping does not take effect (https://docs.docker.com/network/host/)

We could implement a warning, but let's rather focus on more important issues
