### ISSUE TITLE
Unable to use docker_registry_image with my public image

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#86]
<i>This issue was originally opened by @Leon99 as https://github.com/hashicorp/terraform-provider-docker/issues/140. It was migrated here as a result of the community provider takeover from @kreuzwerker. The original body of the issue is below.</i><hr>
### Terraform Version
```
Terraform v0.11.13
+ provider.docker v1.1.1
```

### Affected Resource(s)
`docker_registry_image`

### Terraform Configuration Files
```hcl
data "docker_registry_image" "myimage" {
  name = "myuser/myimage:latest"
}
```

### Expected Behavior
It works without errors

### Actual Behavior
` Got error when attempting to fetch image version from registry: Got bad response from registry: 401 Unauthorized`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by suzuki-shunsuke** [comment]
https://github.com/kreuzwerker/terraform-provider-docker/blob/3036de30684e8966f87aca4597ebea587d3ebed4/docker/data_source_docker_registry_image.go#L71

`Got bad response from registry: 401 Unauthorized` is a response of API.
So we don't have to fix this.

I think we can close this issue.

**Comment by suzuki-shunsuke** [comment]
I close this issue. Please reopen if you need.
