### ISSUE TITLE
upload attribute cannot be used inside a module

### ISSUE THREAD

**Issue by mavogel** [kreuzwerker/terraform-provider-docker#90]
<i>This issue was originally opened by @captn3m0 as https://github.com/hashicorp/terraform-provider-docker/issues/129. It was migrated here as a result of the community provider takeover from @kreuzwerker. The original body of the issue is below.</i><hr>
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
Terraform v0.11.8
+ provider.cloudflare v1.0.0
+ provider.digitalocean v0.1.3
+ provider.docker v2.0.0
+ provider.local v1.1.0
+ provider.postgresql v0.1.2
+ provider.random v2.0.0
+ provider.template v1.0.0
+ provider.tls v1.2.0
```

I'm on a custom fork based on latest master.

### Affected Resource(s)
Please list the resources as a list, for example:
- `docker_container`

### Terraform Configuration Files
```hcl
module "test" {
  source = "../modules/container"

  uploads = [
    {
      content = "HELLO"
      file    = "/tmp/hello"
    }
  ]
}

// And inside the container module:

resource "docker_container" "container" {
  name       = "${var.name}"
  upload = ["${var.uploads}"]
}
```

### Debug Output
```
Error: module.container: "upload.0.content": required field is not set
Error: module.container: "upload.0.file": required field is not set
```

### Expected Behavior
It should be possible to pass var.uploads and use it inside a module to create a docker_container resource.

### Actual Behavior
Terraform errors out.

**Comment by suzuki-shunsuke** [comment]
https://www.terraform.io/docs/configuration/attr-as-blocks.html
https://www.terraform.io/docs/configuration/expressions/dynamic-blocks.html

I think this is a problem of not this provider but Terraform.
And from v0.12, we can use the dynamic block.

```
main.tf
container/
  main.tf
```

main.tf

```tf
module "test" {
  source = "./container"

  uploads = [
    {
      content = "HELLO"
      file    = "/tmp/hello"
    }
  ]
}

terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.10.0"
    }
  }
}

# Configure the docker provider
provider "docker" {
}
```

container/main.tf

```tf
resource "docker_container" "container" {
  name = "alpine"
  dynamic "upload" {
    for_each = var.uploads
    content {
      content = upload.value["content"]
      file    = upload.value["file"]
    }
  }
  image = docker_image.alpine.latest
}

variable "uploads" {
}

resource "docker_image" "alpine" {
  name = "alpine:3.11.6"
}
```
